### PR TITLE
Fix OVAL enumerations

### LINKED ISSUE #1634: [SCAP.R.1200] can't evaluate CPEs that contains other platform checks
#### Description of Problem:
Evaluation of r1200-datastream.xml [SCAP 1.3 validation test suite](https://csrc.nist.gov/CSRC/media/Projects/scap-validation-program/documents/SCAP1.3ValidationTestContent_1-3.0.0.0.zip) fails because it can't determine whether a check is applicable because the CPE checks contains an Mac OS X check.

#### OpenSCAP Version:
1.3.4

#### Steps to Reproduce:

1.  oscap xccdf eval --benchmark-id xccdf_gov.nist_benchmark_r1200-1   --results-arf results_arf.xml requirements/R1200/r1200-datastream.xml
2. 
3. 

#### Actual Results:
W: oscap: Unknown OVAL family subtype: plist510

OpenSCAP Error: Unknown test type oval:gov.nist.validation.cpe.oval:tst:1102. [/builddir/build/BUILD/openscap-1.3.4/src/OVAL/oval_test.c:395]
Can't import OVAL definition model 'cpe_applicability_validation_content-cpe-oval.xml' for CPE applicability checking [/builddir/build/BUILD/openscap-1.3.4/src/CPE/cpe_session.c:113]

#### Expected Results:
no errrors

#### Additional Information / Debugging Steps:
The results of rules xccdf_gov.nist_rule_r1200_cpe_applicability-8, xccdf_gov.nist_rule_r1200_cpe_applicability-10 and xccdf_gov.nist_rule_r1200_cpe_applicability-12 should be notapplicable and other rules are not selected. The scanner gives correct rule results now. It seems like the error message doesn't affect the rule results in this example.

Moreover, a similar problem happens also when running `oscap xccdf eval --benchmark-id xccdf_gov.nist_benchmark_r1200-4 --results-arf  arf.xml requirements/R1200/r1200-datastream.xml`

### LINKED ISSUE #1636: [SCAP.R.1200] applicable rules are evaluated as notapplicable
### Description of Problem:

Evaluation of xccdf_gov.nist_benchmark_r1200-4 benchmark from r1200-datastream.xml from [SCAP 1.3 validation test suite](https://csrc.nist.gov/CSRC/media/Projects/scap-validation-program/documents/SCAP1.3ValidationTestContent_1-3.0.0.0.zip) gives unexpected results.

#### OpenSCAP Version:
1.3.4

#### Steps to Reproduce:

1. oscap xccdf eval --benchmark-id xccdf_gov.nist_benchmark_r1200-4 --results-arf    results_arf.xml requirements/R1200/r1200-datastream.xml

#### Actual Results:

Rules xccdf_gov.nist_rule_r1200_cpe_applicability-1000 and  xccdf_gov.nist_rule_r1200_cpe_applicability-2000 have a wrong result "notapplicable". Moreover, a lot of errors are printed.

```
Title   Test the Applicability processing capabilities
Rule    xccdf_gov.nist_rule_r1200_cpe_applicability-1000
W: oscap: Unknown OVAL family subtype: plist510
Result  notapplicable

Title   Test the Applicability processing capabilities
Rule    xccdf_gov.nist_rule_r1200_cpe_applicability-2000
W: oscap: Unknown OVAL family subtype: plist510
Result  notapplicable

Title   Test the Applicability processing capabilities
Rule    xccdf_gov.nist_rule_r1200_cpe_applicability-8000
W: oscap: Unknown OVAL family subtype: plist510
Result  notapplicable

OpenSCAP Error: Unknown test type oval:gov.nist.validation.cpe.oval:tst:1102. [/builddir/build/BUILD/openscap-1.3.4/src/OVAL/oval_test.c:395]
Can't import OVAL definition model 'cpe_applicability_validation_content-cpe-oval.xml' for CPE applicability checking [/builddir/build/BUILD/openscap-1.3.4/src/CPE/cpe_session.c:113]
Unknown test type oval:gov.nist.validation.cpe.oval:tst:1102. [/builddir/build/BUILD/openscap-1.3.4/src/OVAL/oval_test.c:395]
Can't import OVAL definition model 'cpe_applicability_validation_content-cpe-oval.xml' for CPE applicability checking [/builddir/build/BUILD/openscap-1.3.4/src/CPE/cpe_session.c:113]
Unknown test type oval:gov.nist.validation.cpe.oval:tst:1102. [/builddir/build/BUILD/openscap-1.3.4/src/OVAL/oval_test.c:395]
Can't import OVAL definition model 'cpe_applicability_validation_content-cpe-oval.xml' for CPE applicability checking [/builddir/build/BUILD/openscap-1.3.4/src/CPE/cpe_session.c:113]
```

#### Expected Results:

The rules are evaluated as follows and no errors are printed.
xccdf_gov.nist_rule_r1200_cpe_applicability-1000 pass
xccdf_gov.nist_rule_r1200_cpe_applicability-2000 fail
xccdf_gov.nist_rule_r1200_cpe_applicability-8000 notapplicable

#### Additional Information / Debugging Steps:

The rules xccdf_gov.nist_rule_r1200_cpe_applicability-1000  and xccdf_gov.nist_rule_r1200_cpe_applicability-2000 are in a xccdf:Group that has a CPE  `<xccdf:platform idref="cpe:/o:vendor:os:10"/>`. This CPE is defined in the same datastream file and is always true. Similarly, xccdf_gov.nist_rule_r1200_cpe_applicability-8000 has a CPE that is always false. It's a simple variable check. However, OpenSCAP fails to load the CPE OVAL due to errors printed on stderr and therefore assumes everything is notapplicable.

This issue can be related to or even it can be a superset of https://github.com/OpenSCAP/openscap/issues/1634

### PR DESCRIPTION
**Pull request by evgenyz**
A bit of update in terms of the latest OVAL entities and families enumeration. Some messages moving around log levels. Check out the details in commit messages.

Fixes #1636. Fixes #1634. Partially affects #1422.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@evgenyz Mostly looks fine.

The commit `Fix the test for CURL's gzip headers` looks unrelated. How is it related?

Also, I'm not sure whether it fully fixes #1422 because:
```
[jcerny@localhost openscap{pr/1675}]$ c_oscap   oval analyse --results t.xml definition_nl.xml syschar_nl.xml 
W: oscap:     Unsupported data type: ios_version.
```
Maybe put #1422 on hold?

**Comment by evgenyz** [comment]
Yeah, I put fixes a little bit prematurely. As I figured out later as well we will have to add more fixes for that issue.

**Comment by evgenyz** [comment]
GZIP is completely unrelated but it fails for me sometimes and I don't think it really deserves its own PR.

**Comment by jan-cerny** [comment]
> GZIP is completely unrelated but it fails for me sometimes and I don't think it really deserves its own PR.

It's a good custom to not mix unrelated stuff in PRs even if very small.

**Pull request merged**
