### PR TITLE
Fix a segmentation fault

### PR DESCRIPTION
**Pull request by jan-cerny**
We need to check if the pointers are NULL.

Fixes: #1735

Also fixes similar occurences of XMLXPath(Node)Eval.

### CODE REVIEW

**Comment by jan-cerny** [comment]
The CI fail is valid

```
170/257 Test #170: DS/schematron/schematron.sh ........................................................***Failed    0.43 sec
File '/home/jenkins/workspace/openscap-pull-requests-multi/label/rhel8/tests/DS/schematron/simple_ds_xccdf_schematron_error.xml' line 66: Element '{http://checklists.nist.gov/xccdf/1.2}Profile': No match found for key-sequence ['xccdf_com.example.www_rule_test-pass'] of keyref '{http://checklists.nist.gov/xccdf/1.2}profileExtIdKeyRef'.
OpenSCAP Error: Invalid SCAP Source Datastream (1.3) content in /home/jenkins/workspace/openscap-pull-requests-multi/label/rhel8/tests/DS/schematron/simple_ds_xccdf_schematron_error.xml. [../src/source/oscap_source.c:353]
```

but it's clearly caused by https://github.com/OpenSCAP/openscap/pull/1732

I wonder why jenkins didn't fail in #1732.

**Comment by jan-cerny** [comment]
blocked by https://github.com/OpenSCAP/openscap/pull/1737 which should fix the test

**Comment by evgenyz** [comment]
> blocked by #1737 which should fix the test

Merged

**Comment by jan-cerny** [comment]
I have rebased this PR on the top of the current maint-1.3 branch.

**Comment by evgenyz** [comment]
@openscap-ci test this, please

**Comment by evgenyz** [comment]
Okay, it seems to be OK. Thanks for the fix!

**Pull request merged**
