### PR TITLE
Dpkg info offline mode, fixes

### LINKED ISSUE #1367: dpkginfo_free_reply should return NULL
- Is this an issue with SCAP Workbench?
    - don't know
- Is this an issue with SCAP Security Guide (i.e., related to the content of scans, not the scanner proper)?
    - don't know
- Is this an issue during the OS installation process?
    - don't know

Thanks!

#### Description of Problem:
When run `oscap oval collect --id ID OVAL.XML`, prog will crash. By debugging, I found this function messed the caller's stack because it doesn't return value as its function signature declared.

#### OpenSCAP Version:
git clone in 6/20/2019

#### Steps to Reproduce:

1. oscap oval collect --id ID OVAL.XML
   where id is oval:com.ubuntu.disco:obj:2017111090000000
2.

#### Actual Results:
crash

#### Expected Results:
not crash

#### Additional Information / Debugging Steps:
n/a

### PR DESCRIPTION
**Pull request by evgenyz**
Adding PROBE_OFFLINE_OWN support was very easy. But still there is a problem here: I'm unable to check any pkgcache.bin, be it a mounted file from VM or local file without any chroot shenanigans. The `new pkgCache (dpkg_mmap);` call always returns error 'The package cache file is corrupted'.

I'll just leave it here in case someone could shed some light on the matters.

This PR will also fix #1367

### CODE REVIEW

**Comment by evgenyz** [comment]
BTW, @pschneiders can you look at this PR as well? You might be interested in the fix commit at least.

**Comment by pschneiders** [comment]
Currently this PR branch is the only one that builds and runs cleanly for me on Debian.  It fixes the errors in my ComplianceAsCode PR and compiles without changes due to the CAP_LIBRARIES fix.  Let me know if I can do anything specific to verify the specific intentions of this patch.

**Comment by pschneiders** [comment]
@sbjornaas777 can you assist with this

**Comment by evgenyz** [comment]
OK. We will iron out offline mode later, with specific test.

**Pull request merged**
