### PR TITLE
Show severity in HTML guide

### PR DESCRIPTION
**Pull request by mpreisler**
Ran into this today when demoing HTML guide in a meeting. No idea why we didn't show severity in HTML guide.

I also have to say that the HTML guide looks much worse than our HTML report. And the filtering, searching and grouping features are not there. Wish we could bring some of those features to the HTML guide in the future.

I also sneaked in a bugfix. In HTML report we just assume severity attribute is there. This is not guaranteed by the specification! If severity is missing we should assume it's "unknown". I have made changes so that that's what gets displayed in HTML report and HTML guide.

image

### CODE REVIEW

**Comment by mpreisler** [comment]
> I have one nitpick to consider though - "identifier" and "references" has some vertical space around. But newly added severity is glued to identifiers field. Can we keep the vertical pause there for consistency reasons?

I have also noticed that but I have no clue what causes this. In the code it's all `div` elements with no special styling that could cause this space. Any suggestions how to fix this appreciated.

**Comment by yuumasato** [comment]
Adding a paragraph this fixes the vertical spacing.
screenshot from 2017-01-16 11-05-41

**Comment by mpreisler** [comment]
@yuumasato Could you please just push that to my branch so I don't have to replicate your changes?

**Comment by mpreisler** [comment]
I have wrapped severity in `<p>` element. Anything else?

**Comment by yuumasato** [comment]
@mpreisler Actually I just edited the HTML in place in the browser.
And I guess that's just it, a `<p>`, element.

**Comment by jan-cerny** [comment]
@mpreisler I have reviewed and tested this pull request and it looks good to me.

One nitpick though. The labels "Rationale:" and "Remediation Shell script:" start with a capital letter, whereas "references", "severity", "warning" and "identifiers" start with a small letter. I think it should be consistent.

**Comment by mpreisler** [comment]
@jan-cerny You are not the first to notice that, it's a known issue that goes back to the HTML report and guide rewrite. The code that writes that out is shared between report and guide and in report we do capitalize.

It is unrelated to this PR, perhaps somebody else can fix that in a separate PR.

**Comment by jan-cerny** [comment]
@mpreisler OK, ACK Then,

I have created an issue for the nitpick problem https://github.com/OpenSCAP/openscap/issues/655

**Pull request merged**
