### PR TITLE
CMake papercuts

### PR DESCRIPTION
**Pull request by evgenyz**
Just some minor fixes for CMake warnings and WIN32 guardian for CPack's WIX generator

### CODE REVIEW

**Comment by redhatrises** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
@openscap-ci add to whitelist

**Comment by evgenyz** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
The CI fail is unrelated and it's caused by bug fixed in https://github.com/OpenSCAP/openscap/pull/1333

**Pull request merged**
