### PR TITLE
Add user manual for oscap

### PR DESCRIPTION
**Pull request by msrubar**
This is just a merge of following three texts plus some other changes:
  * RHEL official doc,
  * DOCUMENTATION section from the open-scap.org,
  * and @lhorakov previously written text.

### CODE REVIEW

**Comment by msrubar** [comment]
@isimluk Section 1 and 2 should be ready for the review now.

**Comment by mpreisler** [comment]
Do we plan to build and install the manual as part of `make install`?

**Comment by isimluk** [comment]
Michal, I am not sure we can include the icons to the LGPL project. Can you assert these icons can be distributed freely?

**Comment by msrubar** [comment]
@mpreisler I'll make this happen in another commit/PR
@isimluk I think that getting rid of them will save some cycles :)

**Comment by isimluk** [comment]
@msrubar Thanks! Then, we can merge this once you remove the icons.

I have reviewed whole document and I have identified many places which could be improved. However, let's not focus on them for now. There is nothing conceptually wrong. 

I like the overall structure of the document. Having this in git is big improvement in my eyes.

Thanks!

**Comment by msrubar** [comment]
@isimluk Fixed all the issues. Should be ready to be merged now. 

I also saw a few places that could be improved but as you said I decided not to try to change the whole world in this PR.

**Comment by isimluk** [comment]
Perfect. Thank You!

**Pull request merged**
