### PR TITLE
Packit: add CentOS Stream 8 and 9 build targets

### PR DESCRIPTION
**Pull request by matusmarhefka**
Summary of updates in this PR:
* remove depracated `synced_files` key
* enable CentOS Stream build and tests targets
* enable testing on Testing Farm

### CODE REVIEW

**Comment by jan-cerny** [comment]
Great!

Where is the test that we see in the testing farm defined?

**Comment by matusmarhefka** [comment]
> Great!
> 
> Where is the test that we see in the testing farm defined?

There is only one test in the `tests` job which verifies that package can be installed on the selected composes: https://gitlab.com/testing-farm/tests/-/tree/main/packit

**Comment by jan-cerny** [comment]
@matusmarhefka So now what remains to be done here?

**Comment by matusmarhefka** [comment]
> @matusmarhefka So now what remains to be done here?

I would wait for the fix of the CentOS Stream 9 compose which needs to be done by Testing Farm team. It is in progress and when the issue is fixed I will rerun the job to verify it.

**Comment by matusmarhefka** [comment]
@jan-cerny Issue with CentOS Stream 9 is fixed and the PR is ready for review/merge.

**Review by jan-cerny — APPROVED** [review]
amazing and great contribution

**Pull request merged**
