### PR TITLE
opensuse leap is an opensuse product, use the opensuse assigned CPE f…

### PR DESCRIPTION
**Pull request by msmeissn**
…rom /etc/os-release

add opensuse leap 42.2

(do you also want a pull rq for maint-1.2?)

### CODE REVIEW

**Comment by jan-cerny** [comment]
@msmeissn Thank you for proposing a pull request.

The patch LGTM.

Usually such change should go only into master, but I think that this can go to maint-1.2, because this is very similar case to https://github.com/OpenSCAP/openscap/pull/552. There we also changed CPE IDs in a stable branch to comply with assigned IDs. @mpreisler Do you agree?

**Comment by mpreisler** [comment]
@jan-cerny If these IDs are NIST assigned official CPE IDs I agree.

**Comment by mpreisler** [comment]
Just checked and this patch goes against official CPE ID naming.

```
$ grep "leap" official-cpe-dictionary_v2.3.xml | grep novell
  <cpe-item name="cpe:/o:novell:leap:42.0">
    <cpe-23:cpe23-item name="cpe:2.3:o:novell:leap:42.0:*:*:*:*:*:*:*"/>
  <cpe-item name="cpe:/o:novell:leap:42.1">
    <cpe-23:cpe23-item name="cpe:2.3:o:novell:leap:42.1:*:*:*:*:*:*:*"/>
```

In other words we currently use the NIST CPE naming and this patch would change that to something custom.

**Comment by msmeissn** [comment]
NIST currently uses o:novell:leap*

I need to work with them

**Comment by ybznek** [comment]
jenkins, test this please again

**Comment by mpreisler** [comment]
@msmeissn I am very reluctant to accept this if it goes against the NIST CPE dictionary.

**Comment by msmeissn** [comment]
I will reopen it once I get the Mitre CPE dict changed

**Pull request closed without merging**
