### PR TITLE
Support absolute oval path - both simple and file:// prefixed

### PR DESCRIPTION
**Pull request by mpreisler**
Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1312831 and https://bugzilla.redhat.com/show_bug.cgi?id=1312824

CC @dahaic

### CODE REVIEW

**Comment by dahaic** [comment]
Hello Martin,
stderr is full of messages.
`OpenSCAP Error: Unable to open file: '/tmp/tmp.BkPU0GO0Xu//tmp/tmp.BkPU0GO0Xu/oval/always-fail/oval.xml' [oscap_source.c:266]
Could not find file /tmp/tmp.BkPU0GO0Xu//tmp/tmp.BkPU0GO0Xu/oval/always-fail/oval.xml: No such file or directory. [sds.c:646]
Unable to open file: '/tmp/tmp.BkPU0GO0Xu//tmp/tmp.BkPU0GO0Xu/test_default_selector.oval.xml' [oscap_source.c:266]
Could not find file /tmp/tmp.BkPU0GO0Xu//tmp/tmp.BkPU0GO0Xu/test_default_selector.oval.xml: No such file or directory. [sds.c:646]`

**Comment by mpreisler** [comment]
@dahaic Hi, thx for checking. I have committed the patch you sent me via email that adds a test and I will get this fixed so that it passes.

**Comment by mpreisler** [comment]
Hmm, I have no idea how this happens but I can indeed reproduce it. Will have to do more digging here before we can merge it.

**Comment by rsprudencio** [comment]
@openscap-jenkins test this please

**Comment by dahaic** [comment]
Code changes looks good, test is passing. ACK

**Pull request merged**
