### PR TITLE
Change test_sysctl_probe_all to succeed for non-root users

### PR DESCRIPTION
**Pull request by rfrohl**
- add blacklist for confidential kernel params
- set PATH explicitly to make sure sysctl is found

fix for #1263

### CODE REVIEW

**Comment by matusmarhefka** [comment]
@rfrohl LGTM. I think your PR should also merge correctly with this PR: https://github.com/OpenSCAP/openscap/pull/1246 Can you please double check?

**Comment by rfrohl** [comment]
@matusmarhefka I am currently busy, will check by end of next week

**Comment by rfrohl** [comment]
@matusmarhefka I actually have one question concerning the handling of branches: is the maint-1.2 merged into maint-1.3 at one point or is there some more complex branching scheme at work here ? Would it be enough to merge your branch into mine or do I have to do something else?

**Comment by matusmarhefka** [comment]
@rfrohl Yes, `maint-1.2` will be merged into `maint-1.3` at on point. See the section **All applied changes must be propagated** in https://github.com/OpenSCAP/openscap/blob/maint-1.3/docs/contribute/versioning.adoc

You don't need to add anything with your PR, it will get merged next time we do `maint-1.2` -> `maint-1.3` merge. I just wanted you to double check that I am not mistaken  :smiley:

**Comment by jan-cerny** [comment]
@matusmarhefka but this PR is opened against maint-1.3, so the patch will never get to maint-1.2

**Comment by jan-cerny** [comment]
@matusmarhefka yes, it will, but this PR is opened against maint-1.3 so if merged, the patch will not get to maint-1.2

**Comment by matusmarhefka** [comment]
@jan-cerny Yes, but 1-2 will be merged into 1.3 and that is where conflicts may happen, right?

**Comment by rfrohl** [comment]
Just merged the maint-1.2 in my local branch. I do get conflicts but nothing where I am at vault(I think):
```
$ git merge upstream/maint-1.2 && git status
On branch fix_1263
You have unmerged paths.
[...]
Unmerged paths:
  (use "git add/rm <file>..." as appropriate to mark resolution)

        deleted by us:   Makefile.am
        both modified:   README.md
        deleted by us:   configure.ac
        deleted by us:   m4/python.m4
        both modified:   src/XCCDF_POLICY/xccdf_policy_remediate.c
        both modified:   tests/API/XCCDF/unittests/test_remediate_python_subs.xccdf.xml
        both modified:   utils/oscap.8
```

@matusmarhefka Is this okay for you or do you want me to check something different?

**Comment by matejak** [comment]
Great job @rfrohl, we would like to merge this soon. Could you just consider one thing? The
```
SYSCTL_BLACKLIST='stable_secret\|vm.stat_refresh\|fs.protected_hardlinks\|...
```
format is quite difficult to read. What about defining
```
SYSCTL_BLACKLIST='
  stable_secret
  vm.stat_refresh
  fs.protected_hardlinks
  ...'
```
with one item per line, preferably alphabetically ordered, and then using
```
SYSCTL_BLACKLIST_REGEX="first_item$(printf '\|%s' $SYSCTL_BLACKLIST)"
```

**Comment by rfrohl** [comment]
@matejak Sure, will try to push this today. Can not promise that I will have the time though.

**Comment by matusmarhefka** [comment]
@openscap-ci ok to test

**Comment by rfrohl** [comment]
@matusmarhefka will investigate this next week

**Comment by matejak** [comment]
@rfrohl Thank you very much for your work, you did the heavy lifting at time when it really came in handy! We are going ahead, merge it as it is, and propose the missing tiny bits in another PR.

**Comment by matejak** [comment]
However, last minute check revealed that this PR targets the `maint-1.3` branch, although this fix should be applied to `maint-1.2` and then it will get into `maint-1.3` when we merge those two branches together (which we do from time to time).
@rfrohl Could you, as the author of the PR, click the `Edit` button next to the PR title, and please [change the target](https://help.github.com/articles/changing-the-base-branch-of-a-pull-request/) to `maint-1.2`?

**Comment by rfrohl** [comment]
@matejak done.

Please note that I developed this against 1.3 because that was the version I have been packaging. Do you need me to close this and open a new one rebased on 1.2 maint?

**Comment by matejak** [comment]
You are right, however, you can try to run `git rebase -i maint-1.2` on your local machine and follow it by `git push --force-with-lease` later. This could do the trick.
Alternatively, you can submit a PR for `maint-1.2` and close this one. If it helps you, we can merge 1.2 into 1.3 this week.

**Comment by rfrohl** [comment]
@matejak  ok, pushed the rebase

**Comment by matejak** [comment]
Well done @rfrohl, thank you for your effort!

**Pull request merged**
