### PR TITLE
oval_cmp_evr_string: Make epoch comparison less strict for dpkg

### PR DESCRIPTION
**Pull request by dodys**
dpkg by default sets epoch to 0 if no epoch is present.

### CODE REVIEW

**Comment by evgenyz** [comment]
Hi! It would be nice to have a test that covers the difference.

**Comment by dodys** [comment]
> Hi! It would be nice to have a test that covers the difference.

I added some tests, let me know what you think about it.

I also think the unittest test_evr_string_missing_epoch.oval.xml should be re-made to actually use evr_string with rpminfo_object instead of dpkginfo_object.

**Comment by evgenyz** [comment]
Sorry for the delay, I'm back and going to review it soon.

**Review by evgenyz — APPROVED** [review]
I've played with this change a bit and can confirm that it as good as it comes. Just one small request: can you please re-base the PR so that we could have all gating tests green here.

**Comment by dodys** [comment]
> I've played with this change a bit and can confirm that it as good as it comes. Just one small request: can you please re-base the PR so that we could have all gating tests green here.

done!

**Pull request merged**
