### PR TITLE
Add RHEL8 CPE to OpenSCAP CPE dictionary

### PR DESCRIPTION
**Pull request by jan-cerny**
RHEL8 Beta has been announced.
https://www.redhat.com/en/blog/powering-its-future-while-preserving-present-introducing-red-hat-enterprise-linux-8-beta

### CODE REVIEW

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
Tests are failing on Fedora 28/29 because of the zombie problem in tests of the `sysctl` probe. I remember @mildass was investigating this some time ago, do we have any information on this subject?

**Comment by jan-cerny** [comment]
The sysctl probe doesn't have problems with zombies. That was process58 probe.

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by yuumasato** [comment]
@openscap-ci test this please

**Comment by yuumasato** [comment]
After python3 fixes to the gating infrastructure this is passing.
Ack.

**Pull request merged**
