### PR TITLE
probes/file: Add debug output & modify test

### PR DESCRIPTION
**Pull request by ybznek**
We have often randomly failed file probe test.
It should help us to find the issue

### CODE REVIEW

**Comment by mpreisler** [comment]
Looks like a minor change, why `maint-1.2`?

**Comment by ybznek** [comment]
@mpreisler Verbose mode doesn't work with maint-1.0 (dD doesn't exist there), and we would need to compile with --enable-debug to see logged messages - it could possibly change tests results. Reading of these log debug files  is more complicated.

I hope we will revert these changes after fixing of issue, currently we don't know where is the problem with file probe.

**Comment by jan-cerny** [comment]
Yes, the verbose mode is not present in the maint-1.0 branch. The file probe has been crashing more and more often recently. Hopefully this will help us.
@mpreisler To clarify, @ybznek created this because we caught a segmentation fault recently in this piece of code,  https://github.com/OpenSCAP/openscap/issues/447

**Comment by jan-cerny** [comment]
LGTM

**Pull request merged**
