### PR TITLE
add missing package for Debian 11

### PR DESCRIPTION
**Pull request by egberts**
Issue #1819

### CODE REVIEW

**Comment by evgenyz** [comment]
I don't get it. First of all, there is no Debian 10 "above". And even if it was there, does it (and also all Ubuntus and other Debians in the group) cover the dependency in a different way?

**Comment by evgenyz** [comment]
And finally, any particular reason to have #1821 on top of it?

**Comment by jan-cerny** [comment]
> I don't get it. First of all, there is no Debian 10 "above". And even if it was there, does it (and also all Ubuntus and other Debians in the group) cover the dependency in a different way?

Moreover, the libxml-xpath-perl is already listed in the list above.

**Comment by egberts** [comment]
well, when i attempted to do a pull request, Github automatically created another issue.

**Comment by egberts** [comment]
shall i redo the pull request by including all of Debian 10 dependent package names to the Debian 11 list ... instead?

**Comment by evgenyz** [comment]
> shall i redo the pull request by including all of Debian 10 dependent package names to the Debian 11 list ... instead?

How about adding Debian 11 to the list of other Debians instead of creating a new section? I'm still not sure what you are trying to achieve.

**Pull request closed without merging**
