### PR TITLE
[WIP] OVAL details in HTML report layout improvement

### PR DESCRIPTION
**Pull request by jan-cerny**
This patch was originally a part of #1426 but it was not a mandatory part of the fix so I decided to split it and submit it as a separate PR.

It will show OVAL definition ID and title in the OVAL details section
of the HTML report. These values will be displayed similarly to
OVAL test ID and title.

However, that created confusing results (see screen shots in comments below). I improved that by using nested unordered lists, which basically mirror the tree structure of an OVAL definition.

We still need to improve the graphics layout, though.

### CODE REVIEW

**Comment by evgenyz** [comment]
OK, so what are your doubts? Or you just want this PR to be merged as it is (why still draft then)?

**Comment by jan-cerny** [comment]
I think that the way the information is presented is ugly and can create confusion.

Especially when a definition is extended by another definition using extend_definition.

Before:
Screenshot_2020-06-04 xccdf_org open-scap_testresult_xccdf_org ssgproject content_profile_ospp OpenSCAP Evaluation Report

After:
Screenshot_2020-06-04 xccdf_org open-scap_testresult_xccdf_org ssgproject content_profile_ospp OpenSCAP Evaluation Report(1)

Notice that you can't see the hierarchy and it feels like some results are missing but in fact they aren't missing.

I think it would help to transform the whole section to a bullet list to reflect the tree structure of OVAL definitions.

**Comment by evgenyz** [comment]
Aha, got it. I'll fiddle around and check what UI options we could have here.

**Comment by jan-cerny** [comment]
If we use the lists, we get better results, and we can group criteria and add their operator and their results. See this example:

Screenshot_2020-06-08 xccdf_org open-scap_testresult_xccdf_org ssgproject content_profile_ospp OpenSCAP Evaluation Report

What do you think?

**Comment by evgenyz** [comment]
I started exactly with this. Obvious problem is (as in any other tree-view with deep branching) – lot of wasted space on the left (would be even more painful when printed). 

You went beyond and introduced another problem: placement of operators. It's hard to understand that they are actually combining upper-level entries, not the checks immediately under them.

**Comment by evgenyz** [comment]
But I like operators, can you please update PR with the latest code? We will iron out the layout.

**Comment by jan-cerny** [comment]
Yes, it definitely needs more work.

**Comment by jan-cerny** [comment]
I think it isn't possible to add just the original idea of "showing the OVAL definition ID" without any PR scope creep or making the report confusing.

I see following options:
1. Use the currently proposed code and on top of it improve the layout by using better CSS - colours, borders, paddings.
2. Apply the "clickable table tree" library, in a similar way that we use it in the report for the list of rules and groups.
3. Close the PR because it makes the report more complex and we have OVAL graph project that visualises the OVAL results better.

I would like to pursue option (1) or (2) because the report is something that users use the most and they start their investigation of failed rules based on the results present there, so having the report very detailed and accurate should help them.

**Pull request closed without merging**
