### PR TITLE
trac#469 Add Python3 support. Fix --srpm-destination

### PR DESCRIPTION
**Pull request by ybznek**

### CODE REVIEW

**Comment by isimluk** [comment]
This commit does three unrelated things. Other than that it looks good to me.

@mpreisler, what do you think?

**Comment by mpreisler** [comment]
Looks good to me, except the target branch.

`scap-as-rpm` is also in `maint-1.1`, is it a deliberate decision to propose to merge this to just `maint-1.2` or is there a reason for that?

**Comment by ybznek** [comment]
Good point, it can be merged with maint-1.1.

**Comment by isimluk** [comment]
Merged to maint-1.1 manually as 98159abd6965d32805e17a859b2d08c6fa42ec8a.

**Comment by mpreisler** [comment]
I am sorry about the misleading comment. `scap-as-rpm` is in maint-1.0, 1.1 and 1.2. I have cherry-picked the commit Simon pushed to maint-1.0 as https://github.com/OpenSCAP/openscap/commit/e93047061d51e1d195b82a4dcd096ec1f86aee7a

**Pull request closed without merging**
