### PR TITLE
Test oscap_string

### PR DESCRIPTION
**Pull request by jan-cerny**

### CODE REVIEW

**Comment by mpreisler** [comment]
Isn't this already part of another branch? Could you please explain why you are proposing this? Do you just want us to cherry-pick the commit to `maint-1.0`?

**Comment by jan-cerny** [comment]
Yes, it is already part of maint-1.2. It is a test written in C testing the oscap_string module. @isimluk have tried to cherry-pick this test from maint-1.2 to maint-1.0, because he had already moved the tested oscap_string module. But  `make distcheck` failed. He asked me if I could fix it and manage to make `make distcheck` passing and he suggested opening a pull request against maint-1.0.

Another way how to do this is: Cherry-pick the test from maint-1.2 to maint-1.0, merge it upstream, then I can make the fix again and will propose it in another pull request.

**Comment by isimluk** [comment]
That's true, I believe having tests in maint-1.0 is useful, as @ybznek needs to make adjustments to `oscap_string` as a part of work on #102.

However I have explicitly asked to do:
```
git checkout maint-1.0
git pull --no-ff
git cherry-pick -x 7907e1c69ec3db99b7d0d557f671916cec1f6350
git cherry-pick -x 43cb8a556354886081cf7dc90430e94407b4007b
make distcheck
```

I was hoping to have cherry-pick commits in maint-1.0. (That would give me some confidence that the commits are really the same and merge before 1.2.6 will be easy). Note that oscap_string came to maint-1.0 as well using `git cherry-pick -x`.

It would be helpful for me to to at least what was the fix needed to make `make distcheck` work again.

**Comment by isimluk** [comment]
What was the fix needed to make make distcheck work again?

**Comment by jan-cerny** [comment]
* Resolve conflict in ac_probes/configure.ac.tpl to include Makefile only oscap_string test but not the glob_to_regex test
* in configure.ac dtto
* Resolve conflict in tests/Makefile.am - `SUBDIRS` variable should not contain `codestyle` and `oval_details` directories, because these directories don't exist in maint-1.0 branch
* in tests/oscap_string/test_oscap_string.sh, source test_common.sh using `. ${srcdir}/../test_common.sh`  The `srcdir` is needed in maint-1.0 to find the sourced script.

**Comment by jan-cerny** [comment]
Reworked this as suggested - separate commits with a cherry-pick reference.

**Comment by isimluk** [comment]
Thanks!

**Pull request merged**
