### PR TITLE
Add OpenEmbedded support

### PR DESCRIPTION
**Pull request by akuster**
This add base support for OpenEmbedded distributions.

### CODE REVIEW

**Comment by evgenyz** [comment]
We are discontinuing maintenance of the internal CPE dictionary: #1683.

**Comment by akuster** [comment]
Did you want a V2 with the CPE directory changes removed?

**Comment by evgenyz** [comment]
> Did you want a V2 with the CPE directory changes removed?

Yep.

**Comment by akuster** [comment]
Thanks. Updates made.

**Comment by evgenyz** [comment]
Ah, one more thing. Please make PR against `maint-1.3` branch.

**Comment by akuster** [comment]
I don't see how to change my branch to maint-1.3 in this request to closing this one.

**Pull request closed without merging**
