### PR TITLE
oscap_acquire use oscap_buffer

### PR DESCRIPTION
**Pull request by ybznek**
Some refactoring...

### CODE REVIEW

**Comment by ybznek** [comment]
I am thinking about it now... maybe using oscap_string instead of oscap_buffer would by cleaner.

**Comment by isimluk** [comment]
Well, I think that the downloaded content may be bzip. Thus, it may contain zeros, that means it is not really string. Or not?

**Comment by isimluk** [comment]
Lgtm.

Though, I did not run tests.

**Comment by mpreisler** [comment]
I would prefer `oscap_string` to be used. The resulting code will be equivalent but easier to read.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
