### PR TITLE
Fix duplication of DISA IDs in HTML report

### LINKED ISSUE #601: HTML report "Group by" menu contains "DISA ID" option twice
I have scanned a Fedora 25 Server system using OpenSCAP 1.2.12 with SCAP Security Guide 0.1.30 for Fedora (common profile} and I have downloaded and displayed the HTML report of the scan in Firefox.

The problem is that in "Group rules by:" menu i can see "DISA ID" twice.

I have run the scan using this command:
```
oscap xccdf eval --results-arf results.xml --oval-results --report report.html --profile common /usr/share/xml/scap/ssg/content/ssg-fedora-xccdf.xml
```

The results and report are attached.
[attach.tar.gz](https://github.com/OpenSCAP/openscap/files/619241/attach.tar.gz)

### PR DESCRIPTION
**Pull request by mpreisler**
Fixes #601 

See https://github.com/OpenSCAP/openscap/issues/601#issuecomment-271005999 for more details.

image

image

image

### CODE REVIEW

**Comment by mpreisler** [comment]
I took the liberty of sorting references by their href attribute. This means that their order is no longer dependent on the order they appear in in the XCCDF file. Hope it's fine to piggyback that in this fix.

**Comment by mpreisler** [comment]
Piggybacked one more minor thing:

image

**Comment by mpreisler** [comment]
@shawndwells feedback would be great here

**Comment by mpreisler** [comment]
@openscap-jenkins test this please

**Comment by rsprudencio** [comment]
Looks better now :smile: 

Waiting for @shawndwells review.

**Comment by mpreisler** [comment]
@rsprudencio I think this can be merged even without Shawn's review, I just wanted to CC him to let him know we are fixing it.

**Comment by shawndwells** [comment]
Sorry, was on travel this week. Looks great!

Would pluralize the CIS and PCI sections, but that's a nitpick. E.g.
``CIS Recommendation`` --> ``CIS Recommendations``

**Comment by mpreisler** [comment]
> Would pluralize the CIS and PCI sections, but that's a nitpick. E.g.
> CIS Recommendation --> CIS Recommendations

Unfortunately that's not trivial to do. We may do it in another PR. The way the code works the ident's name is used verbatim in group-by. We would have to implement new logic that would pluralize it.

**Comment by shawndwells** [comment]
Works for me. Merging :)

**Pull request merged**
