### PR TITLE
Fixed bug in rpm epoch.

### PR DESCRIPTION
**Pull request by jan-cerny**

### CODE REVIEW

**Comment by mpreisler** [comment]
I would really appreciate a test that demonstrates what failed before this fix. That way we will also be sure we don't regress.

**Comment by jan-cerny** [comment]
See https://github.com/OpenSCAP/openscap/pull/64 - this fails before the fix.

**Comment by isimluk** [comment]
I think this can be merged to maint-1.0

**Comment by isimluk** [comment]
Merged as 44e1ae71c680b14c5c78a0737edb626c03b181fe. Thank You!

**Pull request closed without merging**
