### PR TITLE
Removed line that overwrites the original result start time that is s…

### PR DESCRIPTION
**Pull request by kjankov**
…et at the beginning of evaluation

### CODE REVIEW

**Comment by kjankov** [comment]
Fix for issue https://github.com/OpenSCAP/openscap/issues/772

**Comment by jan-cerny** [comment]
I think that this isn't the right fix. It breaks test `tests/API/XCCDF/unittests/test_remediate_simple.sh`.

**Comment by mpreisler** [comment]
@kjankov @jan-cerny any updates here?

**Comment by jan-cerny** [comment]
@mpreisler I don't have any update. I still think it isn't right fix, because it breaks test tests/API/XCCDF/unittests/test_remediate_simple.sh. Therefore we can't merge it now.

**Comment by jan-cerny** [comment]
I think I have a right fix, see https://github.com/OpenSCAP/openscap/pull/804

**Comment by mpreisler** [comment]
Replaced by #804

**Pull request closed without merging**
