### PR TITLE
[Do not merge] maint-1.3 CI test

### PR DESCRIPTION
**Pull request by jan-cerny**

### CODE REVIEW

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
What is the purpose of this PR?

**Comment by mpreisler** [comment]
@jan-cerny Please reopen if this PR still makes sense.

**Comment by jan-cerny** [comment]
@matejak The purpose of this PR was to test CI on maint-1.3.

**Pull request closed without merging**
