### PR TITLE
Changing hard coded libperl path in favor of  FindPerlLibs method

### PR DESCRIPTION
**Pull request by kirotawa**
Changing hard coded libperl paths in favor of  FindPerlLibs method.

### CODE REVIEW

**Comment by redhatrises** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
This is awesome!

Unfortunately, it breaks the Mac OS X build. The CI results https://github.com/OpenSCAP/openscap/pull/1618/checks?check_run_id=1216503252 show that

```
CMake Error at swig/perl/CMakeLists.txt:16 (install):
-- Configuring incomplete, errors occurred!
See also "/Users/runner/work/openscap/openscap/build/CMakeFiles/CMakeOutput.log".
  install TARGETS given no LIBRARY DESTINATION for module target
See also "/Users/runner/work/openscap/openscap/build/CMakeFiles/CMakeError.log".
  "openscap_pm".


CMake Error at swig/perl/CMakeLists.txt:18 (install):
  install PROGRAMS given no DESTINATION!
```

Unless you know the fix for the Mac OS X systems, you will have to have 2 code branches guarder by `if(APPLE)`, where on OS X the old code can be used.

**Comment by kirotawa** [comment]
Thanks @jan-cerny did that if(APPLE) suggestion, hopefully it works now :)

**Review by evgenyz — APPROVED** [review]

**Comment by evgenyz** [comment]
LGTM, thanks!

**Pull request merged**
