### PR TITLE
Allow uname probe in offline mode

### PR DESCRIPTION
**Pull request by akarim22**
Signed-off-by: akarim22 <akarim@microsec.ai>

### CODE REVIEW

**Comment by evgenyz** [comment]
So, what data this probe (based on `sysinfo` call) would collect in the offline mode?

**Comment by akarim22** [comment]
> 

it's sysname, nodename etc
`(gdb) p buf
$1 = {sysname = "Linux", '\000' <repeats 59 times>, nodename = "akarim-IdeaPad-3-15ITL05", '\000' <repeats 40 times>, release = "5.15.0-52-generic", '\000' <repeats 47 times>, 
  version = "#58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022", '\000' <repeats 21 times>, machine = "x86_64", '\000' <repeats 58 times>, domainname = "(none)", '\000' <repeats 58 times>}
`
This is what i got from debugging it. I am not very much familiar with internals of it. but i kept getting these warnings
`Requested offline mode is not supported by uname probe` 
so i looked into other probes e.g. file and tried to mimic same for uname probe. 

any guidance is highly appreciated. TIA

**Comment by evgenyz** [comment]
Well, the problem here is that the information would be collected from the *host* system and would not be entirely relevant to the system that being evaluated (defined with `OSCAP_PROBE_ROOT`). Look at the probes that support offline mode to understand what it really means.

**Comment by evgenyz** [comment]
Can you please provide a bit more context to the problem? 

What kind of content you're trying to evaluate? Why uname probe is used there? Where does it come from? What is the target?

**Comment by evgenyz** [comment]
Closing due to the lack of activity.

**Pull request closed without merging**
