### PR TITLE
Plug a memory leak

### PR DESCRIPTION
**Pull request by jan-cerny**
When there already exists a value under the given key in the hash table, oscap_htable_add doesn't put the value to the hash table and therefore the value isn't freed when the hash table is freed. The caller of oscap_htable_add needs to check if oscap_htable_add failed and in this situation is responsible to free the value.

Addressing:

```
oscap  xccdf eval --profile '(all)' --rule xccdf_org.ssgproject.content_rule_accounts_tmout /usr/share/xml/scap/ssg/content/ssg-fedora-ds.xml --- Starting Evaluation ---

Title   Set Interactive Session Timeout
Rule    xccdf_org.ssgproject.content_rule_accounts_tmout
Result  fail

================================================================= ==85219==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 49 byte(s) in 1 object(s) allocated from:
    #0 0x4a3198 in strdup (/home/jcerny/work/git/openscap/build/utils/oscap+0x4a3198) (BuildId: 329fd48580c8ee52863c16be406cb9d7c3df95db)
    #1 0x7f090491f20c in oscap_strdup /home/jcerny/work/git/openscap/src/common/util.h:312:9
    #2 0x7f090491e9dd in ds_sds_dump_component_ref_as /home/jcerny/work/git/openscap/src/DS/sds.c:510:26
    #3 0x7f090491efce in ds_sds_dump_component_ref_as /home/jcerny/work/git/openscap/src/DS/sds.c:574:8
    #4 0x7f090491f7d3 in ds_sds_dump_component_ref /home/jcerny/work/git/openscap/src/DS/sds.c:601:15
    #5 0x7f0904917305 in ds_sds_session_register_component_with_dependencies /home/jcerny/work/git/openscap/src/DS/ds_sds_session.c:327:10
    #6 0x7f0904a0493c in xccdf_session_load_cpe /home/jcerny/work/git/openscap/src/XCCDF/xccdf_session.c:921:8
    #7 0x7f0904a03dc7 in xccdf_session_load /home/jcerny/work/git/openscap/src/XCCDF/xccdf_session.c:705:14
    #8 0x53333f in app_evaluate_xccdf /home/jcerny/work/git/openscap/utils/oscap-xccdf.c:641:6
    #9 0x52fedb in oscap_module_call /home/jcerny/work/git/openscap/utils/oscap-tool.c:295:10
    #10 0x5307fb in oscap_module_process /home/jcerny/work/git/openscap/utils/oscap-tool.c:389:19
    #11 0x53cee0 in main /home/jcerny/work/git/openscap/utils/oscap.c:88:15
    #12 0x7f090390950f in __libc_start_call_main (/lib64/libc.so.6+0x2750f) (BuildId: 81daba31ee66dbd63efdc4252a872949d874d136)

SUMMARY: AddressSanitizer: 49 byte(s) leaked in 1 allocation(s).
```

### CODE REVIEW

**Comment by evgenyz** [comment]
The change itself makes sense.

But I have a question, though. There are more `oscap_htable_add`s in our code (rg -c oscap_htable_add):
```
src/OVAL/oval_generator.c:1
src/OVAL/probes/independent/yamlfilecontent_probe.c:1
src/OVAL/oval_agent.c:1
src/OVAL/probes/unix/linux/systemdunitdependency_probe.c:1
src/common/list.c:2
src/XCCDF_POLICY/xccdf_policy_resolve.c:1
src/common/list.h:1
src/XCCDF_POLICY/xccdf_policy.c:6
src/XCCDF/benchmark.c:4
src/XCCDF/profile.c:2
src/XCCDF/item.c:1
src/XCCDF/xccdf_session.c:5
src/DS/ds_rds_session.c:1
src/DS/rds.c:1
src/DS/sds.c:2
src/DS/sds_index.c:2
src/DS/ds_sds_session.c:1
src/CPE/cpe_session.c:1
src/XCCDF/result.c:1
src/CPE/cpelang_priv.c:1
tests/API/XCCDF/unittests/test_oscap_common.c:4
``` 
And not all of them handle this problem correctly, as it seems to me. Am I missing something there or you just did not address this issue as a whole for some reason?

**Comment by jan-cerny** [comment]
That's a great point! There might be similar problems. I will look into the occurrences.

**Comment by jan-cerny** [comment]
I have fixed some other occurrences of this problem with `oscap_htable_add`.

There are more remaining occurrences. They have one of the following reasons:

- The preceding code checks that the key doesn't exist in the hash table.
- The insertion to hash table happens only if the key doesn't exist in the hash table.
- The hash table is freed by `oscap_htable_free0` which doesn't free the items from the table, therefore, this hash table isn't the owner of its items.
- The item inserted to the table is on stack, so they can't be freed.
- The code logic is so complex that trying to fix the potential leak would need more detailed refactoring and testing.

**Review by evgenyz — APPROVED** [review]
LGTM. Thank you!

The rawhide test failure is not relevant to the changes.

**Pull request merged**
