### PR TITLE
Make verbose mode a common option for all modules

### PR DESCRIPTION
**Pull request by jan-cerny**
Verbose mode was originally introduced first to `oscap oval` module, because the feature was focused to debugging OVAL evaluation. Later, it was extended to `xccdf eval` and then to various other modules.

To be able to extend the verbose mode, we will make the `--verbose` and `--verbose-log-file` global options. In other words, those 2 options will be applicable to all the modules.

A drawback of this approach could be that many parts of our code are not covered by any verbose messages, which means the verbose mode produces often (almost) empty output.

This PR also reflects this CLI change in manual pages.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@jan-cerny rebase it, please.

**Comment by jan-cerny** [comment]
@cipherboy I have rebased this on top of master.

**Comment by cipherboy** [comment]
@jan-cerny Thanks! I'll look at this tomorrow afternoon.

**Comment by cipherboy** [comment]
Hmmm, so I'm not quite sure I fully like this. 

One issue I see is that `--verbose` _requires_ an verbosity level versus "increasing" the verbosity by default without an argument. I'd suggest making it `--verbose [level=INFO]` instead of `--verbose level` if that makes sense. I think the former would be a lot more intuitive. Also, on the help page:

```bash
$ ./utils/oscap --help
oscap

OpenSCAP command-line tool

Usage: oscap [options] module operation [operation-options-and-arguments]

Common options:
   --verbose <verbosity_level>   - Turn on verbose mode at specified verbosity level.
   --verbose-log-file <file>     - Write verbose informations into file.

oscap options:
   -h --help                     - show this help
   -q --quiet                    - quiet mode
   -V --version                  - print info about supported SCAP versions

Commands:
    ds - DataStream utilities
    oval - Open Vulnerability and Assessment Language
    xccdf - eXtensible Configuration Checklist Description Format
    cvss - Common Vulnerability Scoring System
    cpe - Common Platform Enumeration
    cve - Common Vulnerabilities and Exposures
    cvrf - Common Vulnerability Reporting Framework
    info - info module
```

It does not show the list of verbosity options. As far as I can tell, discovery of verbosity levels occurs when you enter a wrong level _with an otherwise fully valid command_:

```bash
$ ./utils/oscap --verbose 
./utils/oscap: unrecognized option '--verbose'
Usage:    oscap [options] module operation [operation-options-and-arguments]
Commands: ds oval xccdf cvss cpe cve cvrf info 
Help:     oscap -h



$ ./utils/oscap --verbose sdf
Usage:    oscap [options] module operation [operation-options-and-arguments]
Commands: ds oval xccdf cvss cpe cve cvrf info 
Help:     oscap -h



$ ./utils/oscap --verbose sdf xccdf
Usage:    oscap [options] xccdf command [command-specific-options]
Commands: eval resolve validate export-oval-variables generate remediate 
Help:     oscap xccdf -h



$ ./utils/oscap --verbose sdf xccdf eval
ERROR:    XCCDF file need to be specified!
Usage:    oscap [options] xccdf eval [options] INPUT_FILE [oval-definitions-files]
Help:     oscap xccdf eval -h



$ ./utils/oscap --verbose sdf info
ERROR:    SCAP file needs to be specified!

Usage:    oscap [options] info some-file.xml
Help:     oscap info -h


$ ./utils/oscap --verbose sdf info ../../../cipherboy/scap-security-guide/build/ssg-rhel7-ds.xml 
ERROR:    Invalid verbosity level! Verbosity level must be one of: DEVEL, INFO, WARNING, ERROR.
Usage:    oscap [options] info some-file.xml
Help:     oscap info -h
```

So that seems a little silly. I'd definitely prefer these values to be more discoverable.

Also, I'd like `--verbose` to apply globally but be position independent if at all possible. I think this is a common enough use case that we'd want to support:

```bash
$ # do something... and have it fail
$  ./utils/oscap  xccdf eval ../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml 
OpenSCAP Error: Schema file 'xccdf/1.1/xccdf-schema.xsd' not found in path '/usr/local/share/openscap/schemas' when trying to validate '../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml' [../src/source/validate.c:103]
Invalid XCCDF Checklist (1.1) content in ../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml. [../src/source/oscap_source.c:345]
Invalid XCCDF Checklist (1.1) content in ../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml [../src/XCCDF/xccdf_session.c:629]


$ # It failed, so I want more information about why it failed, so I pass the verbose flag...
$ ./utils/oscap  xccdf eval ../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml  --verbose DEVEL
OpenSCAP Error: Schema file 'xccdf/1.1/xccdf-schema.xsd' not found in path '/usr/local/share/openscap/schemas' when trying to validate '../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml' [../src/source/validate.c:103]
Invalid XCCDF Checklist (1.1) content in ../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml. [../src/source/oscap_source.c:345]
Invalid XCCDF Checklist (1.1) content in ../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml [../src/XCCDF/xccdf_session.c:629]


$ # Oh, right, I have to pass it in the correct place. >_<
./utils/oscap --verbose DEVEL xccdf eval ../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml 
I: oscap: Identified document type: Benchmark [oscap(16279):oscap(7f68c2158ac0):doc_type.c:96:oscap_determine_document_type_reader]
I: oscap: Created a new XCCDF session from a XCCDF Checklist '../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml'. [oscap(16279):oscap(7f68c2158ac0):xccdf_session.c:168:xccdf_session_new_from_source]
D: oscap: Validating XCCDF Checklist (1.1) document from ../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml. [oscap(16279):oscap(7f68c2158ac0):oscap_source.c:342:oscap_source_validate]
OpenSCAP Error: Schema file 'xccdf/1.1/xccdf-schema.xsd' not found in path '/usr/local/share/openscap/schemas' when trying to validate '../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml' [../src/source/validate.c:103]
Invalid XCCDF Checklist (1.1) content in ../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml. [../src/source/oscap_source.c:345]
Invalid XCCDF Checklist (1.1) content in ../../../cipherboy/scap-security-guide/build/ssg-rhel7-xccdf.xml [../src/XCCDF/xccdf_session.c:629]
```

**Comment by jan-cerny** [comment]
I only have moved the option, but I haven't considered next improvements. This is a great feedback. Thank you. I will try to add the default level.

However I'm not sure about the position independent option. I agree that it would be nice, but it might be tricky, because now, it's "almost position independent", which means you can put it anywhere except after last argument (after file name).

**Comment by cipherboy** [comment]
Ahh okay. I'll consider them out of scope for this PR then. :)

**Comment by cipherboy** [comment]
Wow, this is harder than I thought... Hmmm


```bash
$ ./utils/oscap --verbose not-a-verbose-mode info ../../../cipherboy/scap-security-guide/build/ssg-rhel7-ds.xml 
No such module: not-a-verbose-mode
````

But without works so much better....
```
./utils/oscap --verbose info ../../../cipherboy/scap-security-guide/build/ssg-rhel7-ds.xml 
I: oscap: Identified document type: data-stream-collection
Document type: Source Data Stream
Imported: 2018-07-30T10:30:58
```

**Comment by jan-cerny** [comment]
@cipherboy when we make verbosity level an optional argument, there is no way for the parser to recognize if the next argument is invalid verbosity level or invalid module. We could do some forward scanning that will check the rest of parameters and if it finds name of existing module there it would give a better error message.

Other projects solve it different way: they have `-v`, `-vv`, `-vvv`, `-vvvv`, the more `v`s the more verbose the output is.

**Comment by jan-cerny** [comment]
I can't find why the latest commit broke Windows build. AppVeyor reports no error, just a lot of new warnings in accesstoken_probe, but there was no chang in the accestoken probe since it's introduction in April.

**Comment by cipherboy** [comment]
@jan-cerny wrote:
> Other projects solve it different way: they have `-v`, `-vv`, `-vvv`, `-vvvv`, the more vs the more verbose the output is.

Ahh right. The other way is `--flag=value` (and requiring the equals sign to specify a value, so `--verbose=DEVEL` which is used in e.g., `gssproxy` for `--debug-level=<number>`). We don't currently use an equal sign in any of our command line options (according to `man oscap`), so let's not do that. 

Hmmm... In which case, since db4a6413ff11441b5f7fadbea208236f0fd05831 is a separate commit, let's drop it for now and we'll take an AI to think about how to clean up this interface a little more.

**Comment by jan-cerny** [comment]
Yeah, I wanted to avoid the "equal sign" option, because we don't have it anywhere else. On the other hand, it's easier to implement it correctly, because the equal sign allows you to distinguish between the option and the next argument.

**Comment by jan-cerny** [comment]
Anyway, it will be better to drop the latest commit (db4a641) from here. I think it can be acceptable if we just document the possible values in man page and help.

**Comment by cipherboy** [comment]
Fair enough. I'm merging based on my earlier review and db4a641 being dropped. We can improve the CLI more later. :)

**Pull request merged**
