### PR TITLE
add opensuse 42.2

### PR DESCRIPTION
**Pull request by nevion**

### CODE REVIEW

**Comment by ybznek** [comment]
test this please

**Comment by jan-cerny** [comment]
@openscap-jenkins test this please

We had some issues with Jenkins, which is a server that runs the builds and tests for us. The failure looks unrelated to your pull request. I will try to restart the test job.

**Comment by jan-cerny** [comment]
Also I think it would be better if you could reopen this pull request against maint-1.2 branch.

Maint-1.2 is the current maintenance branch. In master branch we include mostly only experimental changes or patches breaking backward compatibility. Your patch seems harmless, so it can go to maint-1.2. Moreover, patches proposed to master branch won't get to maintenance branches, so it wouldn't get to users in upcoming releases.

**Comment by mpreisler** [comment]
Merged manually into `maint-1.2`. See https://github.com/OpenSCAP/openscap/commit/81adcdb866b61066f5dd32827f334a80fab99169

Thank you for your contribution, @nevion !

**Pull request closed without merging**
