### PR TITLE
Outsourced the pthreads feature check and setup.

### PR DESCRIPTION
**Pull request by matejak**
Moved from our custom autoconf code to a [specialized macro](http://git.savannah.gnu.org/gitweb/?p=autoconf-archive.git;a=blob_plain;f=m4/ax_pthread.m4) from [the archive](https://www.gnu.org/software/autoconf-archive/).
This should minimize possible build errors because of `pthreads.`

### CODE REVIEW

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
I have tested this and it detects pthreads and builds well. Thank you!

**Pull request merged**
