### PR TITLE
Added arm64 support in travis

### PR DESCRIPTION
**Pull request by odidev**
- Added ARM64 job in Travis-CI.
- Updated the build wrapper command from **build-wrapper-linux-x86_64** to **build-wrapper-linux-aarch64** for arm64 platform

Signed-off-by: odidev <odidev@puresoftware.com>

### CODE REVIEW

**Comment by jan-cerny** [comment]
There is some abort in test probes/environmentvariable58/test_probes_environmentvariable58.sh. Do you have an idea what's going on?

**Comment by evgenyz** [comment]
@odidev Can you please resolve the conflicts and provide some feedback about failing test?

**Comment by odidev** [comment]
Hi,

I have rebased the code and the Travis failure is resolved by it. Please review and share your opinion.

**Comment by evgenyz** [comment]
Okay, so now when we have error out of our way, I would like to ask why this change is needed? I prolongs test suite excution time to 28 minutes 50 seconds. And as far as I understand there are no specific code paths related to this arch. What are the benefits for the project?

**Comment by evgenyz** [comment]
As there was no justification provided I'm closing this PR.

**Pull request closed without merging**
