### PR TITLE
Do not drop empty lines from Ansible remediations

### PR DESCRIPTION
**Pull request by jan-cerny**
We are removing empty lines from generated Ansible Playbook.  It looks
nice, but there is a catch.

Ansible tasks are a YAML snippets. So they contain YAML block scalars,
indicated by a pipe (|). Within these block scalars, the newlines should
be preserved.  By removing the empty lines from the scalars we are
actually changing the meaning of the scalars.

Unfortunately, OpenSCAP doesn't understand YAML, but only reads the
Ansible fix line-by-line as s string. That means it doesn't know when it
reads a block scalar. Therefore we need to stop removing the empty lines
anywhere.

This commit also adds a small test.

Resolves: RHBZ#1795563

### CODE REVIEW

**Comment by jan-cerny** [comment]
The problem with this simple solution is that it adds a lot of newlines to the playbooks. For example. the RHEL7 OSPP playbook grows from 4228 lines by 305 lines to 4533 lines.

We could start removing all the newline characters from the end of the contents of the <fix> element until first non-newline character. What do you think?

**Comment by jan-cerny** [comment]
Bump

**Comment by evgenyz** [comment]
@jan-cerny Makes sense, can't see any drawbacks, but it won't get us much I suppose.

**Comment by vojtapolasek** [comment]
By newlines in playbooks you mean trailing newlines at the end of the file?

**Comment by jan-cerny** [comment]
@vojtapolasek I meant empty lines anywhere in the file. And I propose reducing the trailing newlines at each rule block, i.e. at the end of tasks.

**Comment by vojtapolasek** [comment]
I understand. Although I am not sure why excessive empty lines are a problem.

**Comment by jan-cerny** [comment]
@vojtapolasek They shouldn't be a problem, they only look ugly and increase the file size.

**Comment by jan-cerny** [comment]
OK, let's not do it.

**Comment by evgenyz** [comment]
PR fixes the problem in BZ and we decided not to proceed with micro-optimizations. Merging.

**Pull request merged**
