### PR TITLE
Added schematron files for OVAL 5.11

### PR DESCRIPTION
**Pull request by jan-cerny**

### CODE REVIEW

**Comment by jan-cerny** [comment]
all schematrons were generated automatically

**Comment by mpreisler** [comment]
The second commit simply can't go in. You commented <note> elements even in CPEs and old OVALs.

In my opinion we should patch the schematron and XSD (if necessary) of OVAL 5.11 to be more lenient. It requires less changes and is more manageable than changing all the content files.

**Comment by jan-cerny** [comment]
I agree with you.

**Comment by jan-cerny** [comment]
Reverted

**Comment by mpreisler** [comment]
In this case I think it might be better to `git rebase -i` and just leave out the two last commits. Then `git push --force`.

While it's not a big deal to merge a revert commit it bloats the repository and is not a good practice.

As promised I will work to fix the schemas, will update you here when that's done.

**Comment by jan-cerny** [comment]
OK

**Comment by mpreisler** [comment]
I have changed the schema to be more lenient in https://github.com/OpenSCAP/openscap/commit/8e1f69c0bacb974f604f56a12da5386e1bfa8c8f

**Pull request merged**
