### PR TITLE
Changed masking behaviour.

### PR DESCRIPTION
**Pull request by jan-cerny**
According to the clarified specification, the "mask" attribute
should not affect oval_definitions section in oval_results.
It says: ... the"oval_definitions" section must not be altered
and must be an exact copy of the definitions evaluated.

### CODE REVIEW

**Comment by mpreisler** [comment]
If specification was just clarified and not altered, why are we fixing this only in maint-1.2?

**Comment by jan-cerny** [comment]
@mpreisler  : That is a good question. I have looked into specification and the OVAL issue https://github.com/OVALProject/Language/issues/67 one again, and I am totally confused about it :-(  It seems to me that this is clarified opposite to 5.10, but altered to some previous version. What shall I do with it? Should I allow this behavior only when OVAL 5.11 document is processed?

**Comment by jan-cerny** [comment]
@mpreisler -
OVAL 5.11 specification says:
... When the mask attribute is set to 'true' on an OVAL Entity or an OVAL Field, the corresponding collected value of that OVAL Entity or OVAL Field MUST NOT be present in the "results" section of the OVAL Results document; the "oval_definitions" section must not be altered and must be an exact copy of the definitions evaluated. ...

OVAL 5.10 specification says:
If the mask attribute is set to 'true', then the observed value of this field must not be presented in the results file.

OVAL 5.9 specification says the opposite of 5.11:
..... In addition to the value being omitted from the copy of the system characteristics file, the copy of the definition file should also omit the value and operation used for testing. ..

Github issues says:
... we removed documentation stating that OVAL Definitions documents must be altered
when applying the mask attribute. At the same time, we removed the documentation
that stated "...the observed value of this field,...must not appear in the
results section of an OVAL Results document.". As a result, it is no
longer clear that the masked entities, in the OVAL Definitions document, should
not be altered. ...........

When I read those citations, I think that the behavior changed between 5.9 and 5.10.  In 5.11 it is just a clarification. I think We should implement this only for OVAL >= 5.10, and keep the old behavior for <= 5.9. 
Am I right?

**Comment by jan-cerny** [comment]
It seems that it is possible to implement this depending on OVAL version.

**Comment by mpreisler** [comment]
Discussed with @jan-cerny . Narrowed the problem down to:

5.11 and 5.10:
> OVAL Results document; the "oval_definitions" section must not be altered and must be an exact copy of the definitions evaluated.

5.9:
> the copy of the definition file should also omit the value and operation used for testing.

In other words, 5.11 and 5.10 require and exact copy, 5.9 requires something to be omitted so the result is not an exact copy.

So we need to have different behavior for OVAL <= 5.9 and OVAL >= 5.10

**Comment by jan-cerny** [comment]
Re-worked the commit. It omits the values only for OVAL 5.9 and older. For 5.10 and newer, it makes an copy of values.

**Comment by jan-cerny** [comment]
Test written.

**Comment by jan-cerny** [comment]
I would use assert_exists also. The test_object_entity_mask_oval_5_9.sh is only copied test_object_etity_mask.sh.

**Comment by jan-cerny** [comment]
Should I change the test scripts to use "assert_exists" ?

**Comment by isimluk** [comment]
No. As I have said: "However, I see similar uses (of direct XPATH) in other tests as well. So this is just a comment." :-)

**Comment by mpreisler** [comment]
Shoudn't we apply this to `maint-1.0` as well since 1.0.x supports OVAL 5.9 and 5.10?

It's a relatively isolated change.

**Comment by jan-cerny** [comment]
Yes it can be applied to maint-1.0, I tried it, it works. The change in behavior can be considered as bugfix.

**Comment by jan-cerny** [comment]
Created another PR against maint-1.0 https://github.com/OpenSCAP/openscap/pull/109

**Pull request closed without merging**
