### PR TITLE
Added a better description to xccdf_session_set_validation() doc.

### PR DESCRIPTION
**Pull request by rsprudencio**

### CODE REVIEW

**Comment by mpreisler** [comment]
The docs are really misleading now, I suggest to separate the 3 modes and add that as a paragraph. Write how it connects the function and the CLI tool.

**Comment by mpreisler** [comment]
Oh, this was already merged.

**Comment by rsprudencio** [comment]
I can patch it. You mean adding '--skip-valid' and FULL_VALIDATION environ to related mode?

**Comment by mpreisler** [comment]
On a second read this is fine and I don't think we need to patch it. It's just that my expectation was slightly different.

**Pull request merged**
