### PR TITLE
Register CPE dictionaries when doing ds sds-split

### PR DESCRIPTION
**Pull request by mpreisler**
These dictionaries are auto-registered when doing xccdf eval so it only makes sense we split them all out when splitting datastreams.

### CODE REVIEW

**Comment by yuumasato** [comment]
Works nicely.
Ack when Jenkins finishes.

**Comment by mpreisler** [comment]
@openscap-jenkins test this please

**Comment by mpreisler** [comment]
Jenkins failed because of process58, fixed by rerunning the tests.
Now it failed because of XCCDF unittests, can't reproduce it on my machine.

@openscap-jenkins test this please

**Comment by mpreisler** [comment]
One of the tests checks for empty stderr when splitting and stderr won't be empty when splitting a datastream without the dictionaries element. I will have to fix that before we can merge this PR.

**Comment by mpreisler** [comment]
```
OpenSCAP Error: No 'dictionaries' container element found in file '/tmp/test_multiple_oval_files_with_same_basename.ds.qyvfiz' in datastream of id 'scap_org.open-scap_datastream_from_xccdf_test_multiple_oval_files_with_same_basename.xccdf.xml'. [../../../../src/DS/ds_sds_session.c:283]
```

**Comment by yuumasato** [comment]
Changes look good to me. Ack when Jenkins finishes.

**Pull request merged**
