### PR TITLE
Fixed bad namespace in unix definitions schema and schematron

### PR DESCRIPTION
**Pull request by jan-cerny**

### CODE REVIEW

**Comment by mpreisler** [comment]
Is this change coming from official sources? If not why isn't it labeled as an openscap fix?

**Comment by jan-cerny** [comment]
This is known OVAL issue https://github.com/OVALProject/Language/issues/235. They have forgotten testing namespace "x-macos" in official OVAL schemas.
This fixes not working "oscap oval validate-xml --schematron".
The make validate command in Fedora SSG caused this error:
```
oscap oval validate-xml --schematron output/ssg-fedora-oval.xml
error
xsltCompileStepPattern : no namespace bound to prefix x-macos-def
compilation error: file /home/jcerny/openscap/schemas/oval/5.11/oval-definitions-schematron.xsl line 4843 element template
xsltCompilePattern : failed to compile 'x-macos-def:authorizationdb_test/x-macos-def:state'
OpenSCAP Error: Could not parse XSLT file '/home/jcerny/openscap/schemas/oval/5.11/oval-definitions-schematron.xsl' [xslt.c:146]
Makefile:63: návod pro cíl „validate“ selhal
make: *** [validate] Chyba 1
```

**Comment by jan-cerny** [comment]
Added a comment explaining this change

**Comment by mpreisler** [comment]
Discussed this with @jan-cerny . We found https://github.com/drothenberg/Language/commit/8f09c86b3bc53e541617e58c2b57ba2af2ba2597 which is different to this change. Jan will change this pull request to reflect the official OVAL 5.11.1 change.

**Pull request merged**
