### PR TITLE
RHBZ #1414303, #1414312: Fix a segfault in rpm probes

### PR DESCRIPTION
**Pull request by jan-cerny**
Function probe_init() can possibly fail and return NULL.
We should check if initialization has been done properly
before we start the function.
Now we don't check the return value, which can possibly lead
to synchronization errors between threads and causes
a segmentation fault in probe_fini().

### CODE REVIEW

**Comment by jan-cerny** [comment]
This goes to maint-1.0 because it's a small bugfix in old code.

**Comment by mpreisler** [comment]
@jan-cerny Shouldn't we start checking for this in all the probes? Not just rpm probes?

**Comment by jan-cerny** [comment]
@mpreisler Yes, we can. I recall in some of probes we already do that, but in most of them we don't. Sometimes it would not be necessary, because sometimes probe_init() functions "never fail" or simply don't initialise anything. But it will definitely make the code less error-prone.

**Comment by mpreisler** [comment]
ACK

**Pull request merged**
