### PR TITLE
Fixes for Evaluation Characteristics

### PR DESCRIPTION
**Pull request by evgenyz**
OSCAP_EVALUATION_TARGET is now stored in `target-facts` as `xccdf:fact:identifier` and `target` is always a hostname (with offline support).

ARF result is always valid.

Network entities are not collected in offline mode.

Identity entities are not collected in offline mode.

### CODE REVIEW

**Comment by evgenyz** [comment]
I have one question here. Do we want to have OSCAP_EVALUATION_TARGET value in ARF?

**Comment by jan-cerny** [comment]
@evgenyz  I like this change very much. I have checked the results and reports and they look fine.


> I have one question here. Do we want to have OSCAP_EVALUATION_TARGET value in ARF? The ai:computing-device does not have any suitable element for this.

Logically, it would make sense to have it there. But, we don't use these elements anywhere. If there is no suitable place let's not add it.


I remember we talked about the fact that the generated ARF is invalid when scanning containers. You have mitigated the cause of it which was the `podman-image://` string in  `<ai:hostname>` element. However, the generated ARF is still invalid due to empty `ai:connections` element. I think it can be easy to fix. Can you check it? Here are the steps to reproduce:
```
[jcerny@thinkpad utils{pr/1519}]$ sudo ./oscap-podman --oscap=/home/jcerny/work/git/openscap/build/oscap_wrapper 096cae65a207 xccdf eval --profile ospp --report report.html --results-arf arf.xml /usr/share/xml/scap/ssg/content/ssg-rhel8-ds.xml

[jcerny@thinkpad utils{pr/1519}]$ oscap ds rds-validate arf.xml 
File 'arf.xml' line 65535: Element '{http://scap.nist.gov/schema/asset-identification/1.1}connections': Missing child element(s). Expected is ( {http://scap.nist.gov/schema/asset-identification/1.1}connection ).
OpenSCAP Error: Invalid ARF Result Datastream (1.1) content in arf.xml. [/builddir/build/BUILD/openscap-1.3.2/src/source/oscap_source.c:346]
```

**Comment by evgenyz** [comment]
> However, the generated ARF is still invalid due to empty `ai:connections` element. I think it can be easy to fix. Can you check it? Here are the steps to reproduce:

Done.

**Comment by jan-cerny** [comment]
@evgenyz Thanks!

**Pull request merged**
