### PR TITLE
Issue #664: Show more information about ARF files in "oscap info"

### PR DESCRIPTION
**Pull request by jan-cerny**
This commit will display additional information about an ARF file,
such as evaluation date, source benchmark and profile, platform CPEs,
result ID.

See the improvement:

Before:
```
[jcerny@thinkpad arf_info]$ oscap info arf.xml
Document type: Result Data Stream

Asset: asset0
 - collection1 -> xccdf1
```

After:
```
[jcerny@thinkpad arf_info]$ oscap info arf.xml
Document type: Result Data Stream
Imported: 2017-03-02T12:05:07

Asset: asset0
	ARF report: xccdf1
		Result ID: xccdf_org.open-scap_testresult_xccdf_org.ssgproject.content_profile_common
		Source benchmark: /usr/share/xml/scap/ssg/content/ssg-fedora-ds.xml
		Source profile: xccdf_org.ssgproject.content_profile_common
		Report request: collection1
		Evaluation started: 2017-03-02T12:02:02
		Evaluation finished: 2017-03-02T12:05:07
		Platform CPEs:
			cpe:/o:fedoraproject:fedora:24
```

### CODE REVIEW

**Comment by mpreisler** [comment]
Strange failure in jenkins, could be related to the changes:
`Exported arf results from xccdf without reference to oval   FAIL: all.sh`

@openscap-jenkins test this again

**Comment by mpreisler** [comment]
@openscap-jenkins test this please

**Comment by mpreisler** [comment]
@jan-cerny Do you think we could do something similar for XCCDF test result? Right know we assume it's a benchmark and we never list the TestResult elements. The code would most likely be closely related to the ARF info code.

**Comment by jan-cerny** [comment]
@mpreisler  The failure in Jenkins is related. The test https://github.com/OpenSCAP/openscap/blob/maint-1.2/tests/API/XCCDF/unittests/test_xccdf_results_arf_no_oval.sh#L20 greps for
 `- collection1 -> xccdf1` which I have removed and replaced by something more meaningful.

Does something depend on keeping that string in stdout? If not, I would change the test and also improve it to test the new feature.

I think that we could do something similar for XCCDF results, because here I also use functions from xccdf_result module. I will look into that and let you know. Thanks for suggestion 👍

**Comment by mpreisler** [comment]
> Does something depend on keeping that string in stdout? If not, I would change the test and also improve it to test the new feature.

I do not think we need to keep that. IMO feel free to change the test.

**Comment by jan-cerny** [comment]
OK, I will change the test.

**Comment by jan-cerny** [comment]
I think it's ready for review.

**Comment by mpreisler** [comment]
Greak work, @jan-cerny ! ACK

**Pull request merged**
