### PR TITLE
Fix compiler errors on older systems

### PR DESCRIPTION
**Pull request by jan-cerny**
Functions pthread_getname_np and pthread_setname_np were introduced
in glibc 2.12. With older versions of glibc used on RHEL5 or SLES11
OpenSCAP failed to compile. This commit adds an autoconf rule
to detect the presence of these functions.

See mail thread on our mailing list https://www.redhat.com/archives/open-scap-list/2016-March/msg00000.html

### CODE REVIEW

**Comment by mpreisler** [comment]
Have you checked that it compiles on RHEL5?

**Comment by jan-cerny** [comment]
@mpreisler This patch fixes the issue with functions pthraed_getname_np and pthread_setname_np. There are other issues that make compiling on RHEL5 impossible. They were discovered by S. Gautam - see https://www.redhat.com/archives/open-scap-list/2016-March/msg00006.html

**Comment by jan-cerny** [comment]
I have added another patch here. With this patch it compiles successfully on my RHEL 5.11, but only if I do `./configure --enable-python=no` because swig gives me tons of errors.

**Comment by mpreisler** [comment]
OK, thank you. ACK

**Pull request merged**
