### PR TITLE
Extend 'oscap info'

### PR DESCRIPTION
**Pull request by matejak**
This PR aims to address #685 by parametrizing the `info` module of the `oscap` binary.

### CODE REVIEW

**Comment by matejak** [comment]
Currently, the `oscap info --profiles <datastream file>` is supported.
As the code contains rather long functions that perform multiple tasks and goto statements, a wider extension of the module would require non-trivial refactoring in order to be maintainable.

**Comment by mpreisler** [comment]
@openscap-ci add to whitelist

**Comment by mpreisler** [comment]
@matejak Please push into your fork, not into upstream.

**Comment by matejak** [comment]
I apologize for not following the guide. The correctly-done PR is #872.
I close this PR and the `oscap_info_extension` branch can be deleted.

**Pull request closed without merging**
