### PR TITLE
Add WRLinux 1019 support

### PR DESCRIPTION
**Pull request by dehuo0**
Add WRLinux 1019 support in CPE directory.

### CODE REVIEW

**Comment by yuumasato** [comment]
@openscap-ci ok to test

**Comment by dehuo0** [comment]
Could someone please help to merge the commits?

**Comment by jan-cerny** [comment]
@dehuo0 yes, i'll take a look it this

**Comment by jan-cerny** [comment]
I have no opportunity to test on Wind River Linux, hopefully you did.
The patch looks good to me. Thanks!

**Pull request merged**
