### PR TITLE
Fix export of overrided oscap_text

### PR DESCRIPTION
**Pull request by yuumasato**
This change allows attributes marked as overriders by
oscap_text_set_override() to be exported.

Exportation of an overrider attribute is conditioned by override_given.
But override_given is only set when an imported attribute has override
capability set. So, when an oscap_text was marked as overrider by
oscap_text_set_set_override() the attribute was never exported.

Related to RHBZ#1320194.

### CODE REVIEW

**Comment by mpreisler** [comment]
Makes sense to me. The worst that can happen here is that we export the attribute when not necessary and that is not a major problem.

ACK but will wait for Jenkins.

**Comment by mpreisler** [comment]
I think the test file in parser unit test needs to be changed, override=false needs to be added so that the exported is exactly the same as imported. Then it should pass.

**Comment by yuumasato** [comment]
Restricted the export of override attribute to true values only. There is no need to export override="true".

**Comment by mpreisler** [comment]
OK, ACK.

**Pull request merged**
