### PR TITLE
First try at adding remarks to the guide

### PR DESCRIPTION
**Pull request by Mab879**
Finishing off the last part #1743.

This adds remarks to the guide HTML.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@openscap-ci add to whitelist

**Comment by evgenyz** [comment]
@Mab879 Is it still actual?

**Comment by evgenyz** [comment]
I mean, I don't see any problems with it, but it somehow stuck in the review phase.

**Comment by Mab879** [comment]
This might be useful if we want to do https://github.com/ComplianceAsCode/content/issues/6889

**Comment by evgenyz** [comment]
@Mab879 Is it still relevant?

**Comment by Mab879** [comment]
> @Mab879 Is it still relevant?

[My comment](https://github.com/OpenSCAP/openscap/pull/1755#issuecomment-1625904656) from July 2023 is still valid.

**Review by evgenyz — APPROVED** [review]

**Pull request merged**
