### PR TITLE
Test: Checking .c sources for #include config.h

### PR DESCRIPTION
**Pull request by ybznek**
https://fedorahosted.org/openscap/ticket/485

### CODE REVIEW

**Comment by mpreisler** [comment]
Haven't tested this yet but `tests/sources/Makefile.am` is missing in the commits I think.

**Comment by ybznek** [comment]
Yes, thanks. I forgot to add Makefile.am to commit.

**Comment by ybznek** [comment]
MG, I have forgot to commit main test file too. Shame on me.

**Comment by mpreisler** [comment]
Could you squash these 2 last commits into d84bdc5 so that every commit builds and checks out fine?

**Pull request merged**
