### PR TITLE
Update release tools to work in master branch

### LINKED ISSUE #1036: Release tools in master branch do not reflect CMake
This problem is probably caused by the fact that release tools were implemented in maint-1.2 after CMake has been merged in master.

### PR DESCRIPTION
**Pull request by jan-cerny**
This commit reflects recent changes in master branch, namely CMake
and dropping Python 2.

Fixes #1036 .

### CODE REVIEW

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by mpreisler** [comment]
Please change previous_version to 1.3.0 as well. It's used for ABI checks and ABI/API checks against maint-1.2 don't make sense for master. Plus we would have to keep updating it if we kept it at 1.2.x as 1.2.x gets more releases.

**Comment by matejak** [comment]
@openscap-ci jenkins test this please

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by mpreisler** [comment]
@openscap-ci test this please

**Comment by matejak** [comment]
ACK.

**Pull request merged**
