### PR TITLE
Update MS Windows Instructions

### LINKED ISSUE #196: Update MS Windows instructions
The instructions in https://github.com/OpenSCAP/openscap/blob/maint-1.0/docs/manual/manual.adoc#building-openscap-for-windows-cross-compilation are not up-to-date.

Martin says that working instructions are at  http://martin.preisler.me/2015/02/openscap-and-scap-workbench-on-windows/

### PR DESCRIPTION
**Pull request by redhatrises**
- Fixes #196

### CODE REVIEW

**Comment by jan-cerny** [comment]
Thank you very much for your contribution. The patch looks good to me. I think it should go to `maint-1.0` branch, because the user manual is maintained there. Check our [versioning policy](https://github.com/OpenSCAP/openscap/blob/maint-1.0/docs/contribute/versioning.adoc).

**Comment by isimluk** [comment]
@redhatrises, thanks for your contribution!

@jan-cerny, On the other hand these instruction are applicable only on master. So it could go to master only.

@mpreisler I would like Martin to review this PR as he was focused on Windows builds in past.

**Comment by mpreisler** [comment]
Agreed with @isimluk, this is master only, we don't support Windows anywhere else.

I am surprised there are errors in the build. Could be that they were introduced with some changes to `maint-1.2`. Will review this soon.

**Comment by redhatrises** [comment]
Thanks guys!

> I am surprised there are errors in the build.
@mpreisler I was too. 

> Could be that they were introduced with some changes to `maint-1.2`.
Most likely unless I am missing a `mingw32` package that wasn't identified or I need an additional `--disable` for some sort of feature.

**Pull request merged**
