### PR TITLE
enable subdir-objects in automake

### PR DESCRIPTION
**Pull request by redhatrises**
- Silences warnings and deprecation notice about subdir-objects

### CODE REVIEW

**Comment by mpreisler** [comment]
Merged manually into `maint-1.0`, see https://github.com/OpenSCAP/openscap/commit/a138dcc3adde1c1fbdeae6b5d0a509bda9d8c5ec

Thanks!

**Comment by mpreisler** [comment]
Had to revert it, this  change breaks the build.

https://github.com/OpenSCAP/openscap/commit/50c9bce237977ec63765df20f87cad6455cc09ac

We will need to revisit this later.

**Comment by redhatrises** [comment]
@mpreisler was this on the master branch that it failed?

**Comment by mpreisler** [comment]
Fails on all branches. The error message from the `master` branch:
```
Making all in unittests
make[5]: Entering directory '/home/mpreisle/d/openscap/tests/API/XCCDF/unittests'
Makefile:1629: ../../../../src/common/.deps/test_oscap_common-alloc.Po: No such file or directory
Makefile:1630: ../../../../src/common/.deps/test_oscap_common-list.Po: No such file or directory
Makefile:1631: ../../../../src/common/.deps/test_oscap_common-util.Po: No such file or directory
make[5]: *** No rule to make target '../../../../src/common/.deps/test_oscap_common-util.Po'.  Stop.
make[5]: Leaving directory '/home/mpreisle/d/openscap/tests/API/XCCDF/unittests'
Makefile:1243: recipe for target 'all-recursive' failed
```

**Pull request closed without merging**
