### PR TITLE
Enable offline scan of some probes 

### PR DESCRIPTION
**Pull request by ybznek**
Should fix also
https://github.com/OpenSCAP/openscap/issues/292

### CODE REVIEW

**Comment by isimluk** [comment]
I don't know. This is hardish to review. It would be great to split this into many pull-requests and review one offline probe per pr.

It would help to have a tests written where applicable or perhaps have the test report for others.

For example probe partition uses `statvfs` and depends on `libblkid`. The `statfs` will imho need proper /proc bindmounted to get the information about current mount points. I don't know what happens when we run this on some chroot directory without proper bindmounts. Actually partition/main depends on correct `/proc`. Perhaps we should include checks like `if offline_mode_on; then assert for bindmounted /proc`

The shadow and password probes should perhaps work. And it should be fairly easy to create a test for them in our upstream test suite. (1) Create /mnt/shadow_offline.XXXXXX/etc/passwd (2) PROBE_CHROOT=/mnt/shadow_offline.XXXXXX. (3) collect and assert for something in that dummy /etc/passwd.

The rpmXXX probes might well work like they are. However, testing (or at least report) would he highly helpful.

I know @dkopecek have done the initial porting of offline probes and he might be good point of contact to discuss this further.

**Comment by mpreisler** [comment]
Have you tested the probes in offline mode?

**Comment by isimluk** [comment]
For the record: passwd & shadow probes are not that easy. They depend on what nss switch says. The `getpwent` queries /etc/passwd, NIS, or LDAP.

Perhaps we should get an ldap into an image set-up the nss switch and then run the scan.

**Comment by ybznek** [comment]
I am investigating partition probe

1) **when I use atomic mount**
in mount dir isn't mounted ```/proc``` - we cannot read mounts
2) **when find PID of container process**
`/proc/$PID/mounts` has same content as `docker exec -t -i a3d74642cf93  cat /proc/mounts ` - it is what we want to read
3) **after 'chroot'** to `/proc/$PID/root` I cannot `cat /proc/mounts `, I can do `cat /proc/1/mounts` - but it will work only if docker container don't use *--pid host*

So for running docker container we can do some work-around to get container process PID and read `/proc/$PID/mounts`. But it requires some new code and provide partition offline scan only for one of many use cases.


Any tips how to deal with it?

**Comment by mpreisler** [comment]
@ybznek, perhaps you could create a few smaller PRs that are easier to review? Let's start with the easiest probes, make sure they work and get them in first. The RPM probes look like they are both very useful and should be easy to support in offline mode.

**Comment by mpreisler** [comment]
Just a note for a future review: @ybznek has split this PR off and this PR now only has the problematic probes. The probes that were tested and work were merged in #331

**Comment by ybznek** [comment]
Unfortunately, it takes quite lot of time without any result.

Partition probe can be possibly available if we/atomic change behavior of offline scanning.

Link to description if in commit messages.

**Comment by mpreisler** [comment]
I am merging this so that the comments are in the code-base. We can later work on each probe separately.

**Pull request merged**
