### PR TITLE
GH Actions: Add Fedora container-based job

### PR DESCRIPTION
**Pull request by evgenyz**

### CODE REVIEW

**Comment by jan-cerny** [comment]
@evgenyz I can see that there are some tests skipped. I assume we need to skip the offline mode tests, but I guess the yamlfilecontent probe tests or SCE tests can be enabled. Could you take a look into this?

**Comment by evgenyz** [comment]
Okay, I think that I holed this ball, we can ignore results from Jenkins

**Comment by evgenyz** [comment]
Err, hold on a sec, rpm probes are skipped in F34. The hell?

**Review by jan-cerny — APPROVED** [review]

**Comment by jan-cerny** [comment]
amazing

**Pull request merged**
