### PR TITLE
Add wmi57 Windows probe

### PR DESCRIPTION
**Pull request by jan-cerny**
This probe implements OVAL wmi57_test from OVAL Windows Definitions schema. This probe allows to query WMI (Windows Management Interface) using queries in WQL language.

OVAL Definitions - specification: https://oval.mitre.org/language/version5.11/ovaldefinition/documentation/windows-definitions-schema.html#wmi57_test

OVAL System Characteristics - specification:
 https://oval.mitre.org/language/version5.11/ovalsc/documentation/windows-system-characteristics-schema.html#wmi57_item

Blocked by https://github.com/OpenSCAP/openscap/pull/1018 , which fixes bugs in `record` element, which is produced by wmi57_probe.

### CODE REVIEW

**Comment by matejak** [comment]
@openscap-ci jenkins test

**Comment by matejak** [comment]
@openscap-ci jenkins test this

**Comment by jan-cerny** [comment]
We really need to fix https://github.com/OpenSCAP/openscap/issues/939, this is annoying.

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Pull request merged**
