### PR TITLE
Fix codeql workflow

### PR DESCRIPTION
**Pull request by paulcacheux**
Fix the install deps step, sourcing package from https://github.com/OpenSCAP/openscap/blob/maint-1.3/docs/developer/developer.adoc#building-openscap-on-linux.

Notes:
- `python-dev` -> `python2-dev`
- fixing this will create a lot of new alerts, this is out of scope for this PR

### CODE REVIEW

**Comment by evgenyz** [comment]
@paulcacheux  Why `python2-dev`? It could (and IMHO should) be built with Python 3.

**Comment by paulcacheux** [comment]
@evgenyz I simply followed the instructions provided in https://github.com/OpenSCAP/openscap/blob/maint-1.3/docs/developer/developer.adoc#1-building-openscap-on-linux subsection "On Ubuntu 16.04, Debian 8 or Debian 9" (the only one talking about ubuntu), and changed `python-dev` to `python2-dev` because on ubuntu 16.04 python is python2.
I think it could be built with python3 as well, but this should be explicit in the documentation first

**Comment by jan-cerny** [comment]
@evgenyz I'm confused, is this PR still needed or do the recent changes in the workflow file fix the same thing?

**Comment by paulcacheux** [comment]
I think the recent changes are enough, closing this

**Pull request closed without merging**
