### PR TITLE
Initial Wind River Linux support

### PR DESCRIPTION
**Pull request by radzy**
Signed-off-by: T.O. Radzy Radzykewycz <radzy@windriver.com>

### CODE REVIEW

**Comment by radzy** [comment]
Couldn't get extend_definition to work in this context though it seems fine in other contexts.  I hope this is suitable as-is, but if the duplication is not acceptable, then I'll do what everyone else seems to be doing and just include a single version number check in cpe/openscap-cpe-oval.xml .

**Comment by radzy** [comment]
Is there any way I can update this PR instead of uploading a new one ?

**Comment by ybznek** [comment]
Hi @radzy,
sorry, I don't know context of this PR.

You can modify current
commits using
```
$ git rebase --interactive origin/master # you can rewrite commits by edit/reword/... reorder them, ...
```
After your changes you can override your remote branch using
```
$ git push <private> -f
```
Where `<private>` is name of your private repository (git remote -v)

When you override your remote branch (this one which is stored on github) PR with this branch will be updated too.

If you are not confident in git operations, you don't forget backup your files.

**Comment by radzy** [comment]
Thanks @ybznek !

**Comment by radzy** [comment]
Anything else I need to do on this, or is it finally OK ?

**Comment by ybznek** [comment]
@radzy Sorry for delay, most of OpenSCAP team isn't available currently.

I don't see any problem with that PR although I haven't checked it with original `/etc/wrlinux-release`.

Thank you for contribution!

**Comment by radzy** [comment]
Thanks, @ybznek !

**Pull request merged**
