### PR TITLE
Don't generate deprecated elements in rpmverifypackage_item.

### PR DESCRIPTION
**Pull request by jan-cerny**

### CODE REVIEW

**Comment by jan-cerny** [comment]
Please How does the probe know what version of OVAL is processing?

**Comment by mpreisler** [comment]
The elements are deprecated. From my understanding that means that users of the results should slowly stop relying on them. Why do we want to stop generating them? That seems a bit excessive to me. They are just deprecated, they haven't been removed in OVAL 5.11.

We should remove them when they are no longer part of the OVAL spec. In the meantime we probably want to generate all the deprecated elements we can.

Or am I missing something?

**Comment by jan-cerny** [comment]
Quotation from the OVAL 5.11 schema:
"This item entity has been deprecated and will be removed in version 6.0 of the language."

This probably means that we shouldn't remove this now.

**Comment by isimluk** [comment]
Right, we should probably not merge this until OVAL 6.0.

**Pull request closed without merging**
