### PR TITLE
Describe how to scan for security patches for RHEL7 in the user manual

### PR DESCRIPTION
**Pull request by mpreisler**

### CODE REVIEW

**Comment by rsprudencio** [comment]
@mpreisler why you set Milestone 1.0.11 for a PR in maint-1.2? Was this a mistake?

**Comment by yuumasato** [comment]
I've tested the instructions and they work properly.

**Comment by rsprudencio** [comment]
Yup, new instructions are correct both for RHEL 6 and RHEL 7. Thanks!

**Comment by mpreisler** [comment]
> @mpreisler why you set Milestone 1.0.11 for a PR in maint-1.2? Was this a mistake?

Yup, that was a mistake on my part.

**Pull request merged**
