### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by jan-cerny**
This PR removes some unused functions, unimplemented functions and unused header files.

These changes have been split out from #1150 .

### CODE REVIEW

**Comment by jan-cerny** [comment]
I cannot reproduce the CI fail.

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by yuumasato** [comment]
@jan-cerny I was able to reproduce it on a freshly installed Fedora  28 VM.
```
XCCDF Results are exported correctly.
Stderr file = /tmp/test_remediation_subs_plain_text_empty.out.Ofu6Ae
Result file = /tmp/test_remediation_subs_plain_text_empty.out.1E9Nx6
Title   Ensure that file exists and it is not executable
Rule    xccdf_moc.elpmaxe.www_rule_1
/root/openscap/tests/API/XCCDF/unittests/test_remediation_subs_plain_text_empty.sh: line 34: 11618 Aborted                 (core dumped) $OSCAP xccdf eval --remediate --results $result $srcdir/${name}.xccdf.xml 2> $stderr
…
The following tests FAILED:
	 29 - API/XCCDF/unittests/all.sh (Failed)
```

**Comment by jan-cerny** [comment]
@ I'm going to investigate further.

**Comment by jan-cerny** [comment]
The issue is reproducible on current upstream master (as of head 2e250171c26abca1d72acf9995146171e63b76b5.) 
I have opened an issue https://github.com/OpenSCAP/openscap/issues/1199 where you can find a traceback.

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
Those functions are indeed not used. In case that need for them arises, they are still reachable in git history.
Good job @jan-cerny for finding those orphans!
This PR is good to merge after merge of #1221 and subsequent rebase  .

**Comment by jan-cerny** [comment]
I have rebased it on master.

**Pull request merged**
