### PR TITLE
Avoids possible dereferencing a null pointer.

### PR DESCRIPTION
**Pull request by jan-cerny**

### CODE REVIEW

**Comment by isimluk** [comment]
Good.

But this error (benchmark missing in policy) is very unlikely and it will be hard to debug/spot when occurs. This function is called only from oscap tool and if it fails it will just return 1 to parent shell and not seying anything.

Please include error reporting like:

```
oscap_seterr(OSCAP_EFAMILY_OSCAP, "Could not find benchmark model for policy when generating fix for %s", ...
```

Thanks!

**Comment by jan-cerny** [comment]
Error message added.

**Comment by mpreisler** [comment]
Adding the xccdf_policy_get_id(policy) to the error message might help when somebody encounters this issue.

Could you please add it to the oscap_seterr call?

oscap_seterr(OSCAP_EFAMILY_OSCAP, "Could not find benchmark model for policy id='%s' when generating fixes.", xccdf_policy_get_id(policy));

policy_id is probably the best identifier we have in this error message.

**Comment by jan-cerny** [comment]
added xccdf_policy_get_id

**Pull request merged**
