### PR TITLE
Fix broken SCE in master branch

### PR DESCRIPTION
**Pull request by jan-cerny**
Commit 1eec7be974ef0dca9fa49b09187adb39f81ff8a3 which bumped soname
has completely broken SCE, beacuse the macro definition in config.h
LT_CURRENT_MINUS_AGE shouldn't be set to 8, but it should be computed
as ${LT_CURRENT} - ${LT_AGE} by CMake.
To do that, we need to move the relevant CMake commands to the root
CMakeLists.txt.

### CODE REVIEW

**Comment by jan-cerny** [comment]
I also think it would be very useful to build and test SCE in our Jenkins jobs to prevent similar problems in future.

**Comment by cipherboy** [comment]
These changes look good, thanks @jan-cerny!

I tested this PR branch. On `HEAD~` before changes:
```bash
ctest -R sce
Test project /home/cipherboy/GitHub/jan-cerny/openscap/build
    Start 86: sce/test_sce.sh
1/8 Test #86: sce/test_sce.sh ....................***Failed    0.19 sec
    Start 87: sce/test_passing_vars.sh
2/8 Test #87: sce/test_passing_vars.sh ...........***Failed    0.14 sec
    Start 88: sce/test_check_engine_results.sh
3/8 Test #88: sce/test_check_engine_results.sh ...***Failed    0.17 sec
    Start 89: sce/test_sce_parse_errors.sh
4/8 Test #89: sce/test_sce_parse_errors.sh .......   Passed    0.45 sec
    Start 90: sce/test_sce_in_ds.sh
5/8 Test #90: sce/test_sce_in_ds.sh ..............***Failed    0.40 sec
    Start 91: sce/test_sce_in_report.sh
6/8 Test #91: sce/test_sce_in_report.sh ..........***Failed    0.24 sec
    Start 92: sce/test_sce_stdout_stderr.sh
7/8 Test #92: sce/test_sce_stdout_stderr.sh ......***Failed    0.16 sec
    Start 93: sce/test_sce_streams_fill.sh
8/8 Test #93: sce/test_sce_streams_fill.sh .......***Failed    0.22 sec

13% tests passed, 7 tests failed out of 8

Total Test time (real) =   1.98 sec

The following tests FAILED:
	 86 - sce/test_sce.sh (Failed)
	 87 - sce/test_passing_vars.sh (Failed)
	 88 - sce/test_check_engine_results.sh (Failed)
	 90 - sce/test_sce_in_ds.sh (Failed)
	 91 - sce/test_sce_in_report.sh (Failed)
	 92 - sce/test_sce_stdout_stderr.sh (Failed)
	 93 - sce/test_sce_streams_fill.sh (Failed)
Errors while running CTest
```

On `HEAD` after changes:
```bash
ctest -R sce
Test project /home/cipherboy/GitHub/jan-cerny/openscap/build
    Start 86: sce/test_sce.sh
1/8 Test #86: sce/test_sce.sh ....................   Passed    0.43 sec
    Start 87: sce/test_passing_vars.sh
2/8 Test #87: sce/test_passing_vars.sh ...........   Passed    0.27 sec
    Start 88: sce/test_check_engine_results.sh
3/8 Test #88: sce/test_check_engine_results.sh ...   Passed    0.24 sec
    Start 89: sce/test_sce_parse_errors.sh
4/8 Test #89: sce/test_sce_parse_errors.sh .......   Passed    0.47 sec
    Start 90: sce/test_sce_in_ds.sh
5/8 Test #90: sce/test_sce_in_ds.sh ..............   Passed    0.40 sec
    Start 91: sce/test_sce_in_report.sh
6/8 Test #91: sce/test_sce_in_report.sh ..........   Passed    0.26 sec
    Start 92: sce/test_sce_stdout_stderr.sh
7/8 Test #92: sce/test_sce_stdout_stderr.sh ......   Passed    0.21 sec
    Start 93: sce/test_sce_streams_fill.sh
8/8 Test #93: sce/test_sce_streams_fill.sh .......   Passed    3.27 sec

100% tests passed, 0 tests failed out of 8

Total Test time (real) =   5.56 sec
```

So they do indeed fix the issue. :) Building and running just these tests takes little time, so I'll look at adding support in #1156 for a SCE build.

**Comment by cipherboy** [comment]
AI [@cipherboy]: make sure scap-workbench supports lib versions greater than 8. I seem to vaguely recall a discussion with @redhatrises about which lib to bind against (in MacOS builds?)....

**Comment by cipherboy** [comment]
@jan-cerny / @redhatrises: 

https://github.com/OpenSCAP/scap-workbench/blob/master/build-for-osx.sh#L7

This is the change I was talking about. I'll file an issue over at scap-workbench.

**Pull request merged**
