### PR TITLE
Fix a python binding install glitch.

### PR DESCRIPTION
**Pull request by matejak**
The SWIG module's name is `openscap_py`.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by jan-cerny** [comment]
This is great and it installs the file. With prefix /tmp/x, I got 
```
$ ls /tmp/x/lib64/python3.6/site-packages/
openscap_api.py  openscap_py.py  _openscap_py.so
```

Waiting for CI, but LGTM.

**Comment by matejak** [comment]
test this please

**Comment by matejak** [comment]
test this please

**Pull request merged**
