### PR TITLE
CVRF Parsing and Export

### PR DESCRIPTION
**Pull request by WesleyCeraso**
Somehow GitHub stopped fetching new commits from Katerina's branch. As I had to create a new PR, I  also rebased it to get rid of conflicts.

### CODE REVIEW

**Comment by WesleyCeraso** [comment]
@mpreisler I have actually found a serious flaw, however it's not exclusive of this PR. We have been using free on memory allocated though libxml2, on linux their implementation uses malloc, so its not a big deal. However, on Windows, it can cause crashes similar to https://github.com/OpenSCAP/openscap/pull/770 and it can impact @jan-cerny work.

When we clone such pointers we use malloc, so it's not possible to replace every free with xmlFree because the memory could have been allocated in both ways.

As I said, the same problem occurs in other parts of the lib, so I think we should not try to fix it here in this PR.

So, what do you think, are ready to merge this PR?

**Comment by WesleyCeraso** [comment]
Oh, it took awhile but GitHub finally updated the original pull request, still, I'll stick to this one.

**Comment by mpreisler** [comment]
> So, what do you think, are we ready to merge this PR?

I will defer to you. There is a bunch of comments in the old PR by you that are not fixed, are you planning to fix them?

**Comment by mpreisler** [comment]
> @mpreisler As I told you, they were more like a To Do list, and I checked every one of them, although I have not responded for each.

OK, this was not clear to me as.

Very well then, let's merge this.

**Comment by jan-cerny** [comment]
Wow :+1:

**Pull request merged**
