### PR TITLE
Add coverage makefile

### PR DESCRIPTION
**Pull request by ybznek**
I don't want to forget about the old Makefile, so I would like to add it to repo.

I would like to have some directory where are stored scripts what helps us with development.

### CODE REVIEW

**Comment by mpreisler** [comment]
I think a wiki page might be better for this than the upstream repo.

**Comment by ybznek** [comment]
Lazy people don't want to copy&paste code from wiki. But if you have strong opinion about it, close this PR.

**Comment by mpreisler** [comment]
Lazy people definitely won't generate coverage.

**Comment by ybznek** [comment]
After discussion with @mpreisler I will move it to wiki.

**Pull request closed without merging**
