### PR TITLE
Easier language and more colors in OVAL details

### PR DESCRIPTION
**Pull request by mpreisler**
I am always confused when reading the OVAL details and have to read the lines several times to understand it. This PR aims to improve that. I use colors to highlight which condition passed and failed. I use simpler language - passed or failed - instead of satisfying and violating.

Before:
image

image

After:
image

image

I feel like this makes the report way easier to read, especially for users not familiar with OVAL and XCCDF. Let me know what you think.

### CODE REVIEW

**Comment by mpreisler** [comment]
One more change:

image

**Comment by shawndwells** [comment]
This will be a forcing function to cleanup OVAL check language... e.g. reading the gpgcheck=0, I kept wondering why the rule failed. Not such a bad thing.

I like this, a lot.

**Comment by rsprudencio** [comment]
Looks really good, I'd just change the size of those boxes to match the font size, looks smaller than the font. If it's not possible or too much of a hassle, we can merge this and add it to TODO list.

**Comment by mpreisler** [comment]
> If it's not possible or too much of a hassle, we can merge this and add it to TODO list.

Not sure how to do that, I just use the class label similar to the OVAL condition box.

**Comment by mpreisler** [comment]
@rsprudencio @shawndwells Anything else that's blocking before we merge this?

**Comment by shawndwells** [comment]
LGTM.

**Comment by shawndwells** [comment]
I would merge this myself, but don't feel comfortable mucking around in core OpenSCAP code + branches. Looking forward to seeing this feature merged!

**Comment by mpreisler** [comment]
> I would merge this myself, but don't feel comfortable mucking around in core OpenSCAP code + branches.

Only one way to fix that :-P

**Comment by rsprudencio** [comment]
Nope, LGTM :)

**Pull request merged**
