### PR TITLE
Solved possible_value elements handling + test

### PR DESCRIPTION
**Pull request by jan-cerny**

### CODE REVIEW

**Comment by isimluk** [comment]
Merged first commit to maint-1.0 as 3d52558e4a30e14473c5682092a001213bd2fe9d

**Comment by isimluk** [comment]
@jan-cerny, it would be great to have better commit message in second commit. Like a description why we need the change or why is the new value more "correct".

**Comment by jan-cerny** [comment]
That is because in specification the description of flag "does not exist" answers more to this use case than flag "error". The specification is here: https://oval.mitre.org/language/version5.11/ovalsc/documentation/oval-system-characteristics-schema.html#FlagEnumeration

**Comment by jan-cerny** [comment]
Build successful on Jenkins

**Comment by isimluk** [comment]
I have reviewed specification and recreated the second commit in maint-1.0 branch as 78e5ddd59fb0693de2cf769cd0823e852bb52f00.

**Comment by jan-cerny** [comment]
Thank you

**Comment by isimluk** [comment]
Merged third commit into maint-1.0 as 01349a12d9f1c0f533d08894deb21eae87588af1. Created small amend as f3e65dc346b4aae18be8876e1581ea64c6ffe869.

**Comment by isimluk** [comment]
third and fifth will have to go to maint-1.2

**Comment by jan-cerny** [comment]
I forgot to say that I tried to re factor the two similar functions oval_varref_elm_to_sexp and oval_varref_attr_to_sexp, but I didn't manage it, because the two functions creates different SEXPs with different format and structure. Merge the functions into one functions would require many changes in many places of code.

**Comment by isimluk** [comment]
Ack. Understood.

**Comment by jan-cerny** [comment]
Added possible_restrictions + test

**Comment by isimluk** [comment]
7th merged to maint-1.0.

remains 3,5,6,8,9,10.

**Comment by isimluk** [comment]
Merged remainder into maint-1.2.

Thanks!

**Pull request closed without merging**
