### PR TITLE
openSUSE CPE update

### PR DESCRIPTION
**Pull request by abergmann**
I've updated the openSUSE CPEs to match the updated entries inside the official NIST CPE dictionary.

### CODE REVIEW

**Comment by mpreisler** [comment]
@openscap-ci add to whitelist

**Comment by mpreisler** [comment]
We might want to keep the old CPEs because people could be relying on them.

**Comment by jan-cerny** [comment]
@mpreisler But if the old CPEs are not official, they cannot be found in https://nvd.nist.gov/products/cpe/search ?

**Comment by abergmann** [comment]
The entry `cpe:/o:novell:leap:42.2` is not listed inside the official CPE dictionary (_I just noticed_). And `cpe:/o:novell:leap:42.1` has a `deprecated_by="cpe:/o:opensuse:leap:42.1"` set.

Both, openSUSE Leap 42.1 and 42.2, reached already End-of-Life (EOL), so only openSUSE Leap 42.3 is currently active.

Therefore (IMHO) the impact of changing the CPEs is quite limited, as the CPE for openSUSE Leap 42.3 was just added by this pull-request.

**Comment by jan-cerny** [comment]
This is interesting.
We maybe should keep the `cpe:/o:novell:leap:42.1` due to backwards compatibility

**Comment by abergmann** [comment]
I've also pushed [scap-security-guide/commit/b491a77](https://github.com/OpenSCAP/scap-security-guide/commit/b491a7779c20be9a3bcd65bc45132df46d2d94fc) that changed the openSUSE Leap 42.1 CPE from "novell" to "opensuse" and it was already accepted.

The "novell" CPEs where never used on the openSUSE side. So my aim was (and still is) to get rid of all incorrect syntax.

**Comment by jan-cerny** [comment]
@abergmann OK, thank you for clarification.

I would merge this.  Do you agree @mpreisler ?

**Comment by abergmann** [comment]
@mpreisler, any update here? Please let me know if something needs to be adjusted.

**Comment by jan-cerny** [comment]
@mpreisler Which of the solutions do you prefer?

**Comment by matusmarhefka** [comment]
Please keep the old novell CPEs, even though they are deprecated we want to retain backward compatibility in `maint-1.2` branch.

**Comment by mpreisler** [comment]
@openscap-ci add to whitelist

**Comment by mpreisler** [comment]
Thank you! Sorry this took so long to review.

**Pull request merged**
