### PR TITLE
Fix shellcheck warning

### PR DESCRIPTION
**Pull request by jan-cerny**
SC2155: Declare and assign separately to avoid masking return values

### CODE REVIEW

**Comment by jan-cerny** [comment]
This shellcheck warning was reported by coverity scan. Similar situation appears on lines 113 and 114, but I won't fix them, because there is a `TODO` comment. I expect that it would be fixed after the `TODO` will be solved.

**Comment by mpreisler** [comment]
Please fix this even for the TODO variables, the same issue is there, the TODO is related to the contents of the variable, not to how it's assigned.

**Comment by jan-cerny** [comment]
OK then

**Comment by jan-cerny** [comment]
I have fixed also the two others.

**Comment by isimluk** [comment]
Thanks!

**Pull request merged**
