### PR TITLE
make default perl install path respect CMAKE_INSTALL_PREFIX

### PR DESCRIPTION
**Pull request by sarnold**
Rebased as requested, same name as the original PR (https://github.com/OpenSCAP/openscap/pull/1999) (sorry about any confusion).

### CODE REVIEW

**Comment by evgenyz** [comment]
Hey! Sorry about it taking so long to review.

I'm a bit confused with minor versions. Here is what I have in Fedora:
```
[ekolesni@ekolesni perl5]$ ls /usr/lib64/perl5 -fl
total 604
drwxr-xr-x. 1 root root    436 May 26  2023 .
dr-xr-xr-x. 1 root root 121852 Dec  6 12:13 ..
drwxr-xr-x. 1 root root     70 May 26  2023 B
drwxr-xr-x. 1 root root     20 May 26  2023 CORE
drwxr-xr-x. 1 root root     14 May 26  2023 File
drwxr-xr-x. 1 root root    142 May 26  2023 IO
drwxr-xr-x. 1 root root     66 May 26  2023 PerlIO
drwxr-xr-x. 1 root root    146 May 16  2023 auto
drwxr-xr-x. 1 root root    678 Oct  2 00:13 vendor_perl
drwxr-xr-x. 1 root root     22 May 26  2023 Sys
drwxr-xr-x. 1 root root     22 May 26  2023 I18N
drwxr-xr-x. 1 root root      8 May 16  2023 Hash
-rw-r--r--. 1 root root  30093 May 16  2023 B.pm
-rw-r--r--. 1 root root   4291 May 16  2023 O.pm
-rw-r--r--. 1 root root  20383 May 16  2023 POSIX.pm
-rw-r--r--. 1 root root  82617 May 16  2023 POSIX.pod
-rw-r--r--. 1 root root   9842 May 16  2023 mro.pm
-rw-r--r--. 1 root root   3988 May 16  2023 Fcntl.pm
-rw-r--r--. 1 root root   1462 May 16  2023 IO.pm
-rw-r--r--. 1 root root   6833 May 16  2023 Errno.pm
-rw-r--r--. 1 root root   3084 May 16  2023 NDBM_File.pm
-rw-r--r--. 1 root root  26015 May 16  2023 DynaLoader.pm
-rw-r--r--. 1 root root   3154 May 16  2023 Config.pm
-rw-r--r--. 1 root root 257699 May 16  2023 Config.pod
-rw-r--r--. 1 root root    409 May 16  2023 Config_git.pl
-rw-r--r--. 1 root root  60309 May 16  2023 Config_heavy.pl
-rw-r--r--. 1 root root   3809 May 16  2023 SDBM_File.pm
-rw-r--r--. 1 root root  16353 May 16  2023 attributes.pm
-rw-r--r--. 1 root root  28710 May 16  2023 re.pm
-rw-r--r--. 1 root root   6136 May 16  2023 lib.pm
-rw-r--r--. 1 root root  16362 May 16  2023 Opcode.pm
-rw-r--r--. 1 root root    997 May 16  2023 ops.pm
```

Can't see any minor-version directories. I wonder, how it will actually function?

**Comment by sarnold** [comment]
What's under `/usr/lib64/perl5/vendor_perl` ?

**Comment by sarnold** [comment]
<sigh> I was hoping this would *not* require distro-specific hacks...

**Comment by sarnold** [comment]
Sorry, I meant using that ^^ by itself.  Which means a bit more cmake foo is required, along with trusting the paths shown in [the cmake docs](https://cmake.org/cmake/help/latest/module/FindPerlLibs.html).  I should be able to push another commit shortly.

**Comment by sarnold** [comment]
After checking a few installs it looks like a free-for-all under the perl install paths with multiple/nested directory trees for what are essentially the same file types so I would expect Fedora to be tolerant enough to accept the versioned subdirectories I see on pretty much any system, starting with the cmake perl paths:

```
-- perl vendorlib: /usr/lib64/perl5/vendor_perl/5.38
-- perl vendorarch: /usr/lib64/perl5/vendor_perl/5.38/aarch64-linux
-- perl sitelib: /usr/local/lib64/perl5/5.38
-- perl sitearch: /usr/local/lib64/perl5/5.38/aarch64-linux
-- perl privlib: /usr/lib64/perl5/5.38
-- perl archlib: /usr/lib64/perl5/5.38/aarch64-linux
```
The current install paths in my top commit can certainly be improved, hopefully after dinner...

**Comment by sarnold** [comment]
If not specified, cmake default install prefix on Linux/mac is `/usr/local` so you must provide another prefix to install to a non-system path as a "normal" user, eg, with something like `-DCMAKE_INSTALL_PREFIX=my/virtualenv/root` in your configure args.

**Comment by evgenyz** [comment]
> Oh yeah, can you run this on fedora and post the perl paths here? Thanks!

I'm not sure what you want me to post exactly, but if you mean output of this:
```
message(STATUS "perl install libdir: ${PERL_VENDORARCH}")
message(STATUS "perl install archdir: ${PERL_VENDORLIB}")
```

then you can check it out yourself for every distro we gate against in CI logs.

**Comment by sarnold** [comment]
Doh!  It's so much fun when everyone gets their own PATHs.

**Comment by sarnold** [comment]
Hmm, after what I said ^^ it feels like it should really default to the value returned by `FindPerlLibs` so I should push another commit soon-ish.

**Comment by evgenyz** [comment]
Great. Thank you!

**Comment by evgenyz** [comment]
The test failure is not relevant to the changes.

**Review by evgenyz — APPROVED** [review]

**Comment by xambroz** [comment]
Hello,
I believe that it might be troublesome placing *.pm file, which dynamically loads arched .so, to the  /usr/share/perl5/vendor_perl/. Same package multiple arches on same disk might be problem. 

For example having i686 package installed next to the x86_64 package would collide in the openscap_pm.pm
having 
i686 package:
/usr/lib64/perl5/vendor_perl/openscap_pm.so
/usr/share/perl5/vendor_perl/openscap_pm.pm 

x86_64:
/usr/lib/perl5/vendor_perl/openscap_pm.so
/usr/share/perl5/vendor_perl/openscap_pm.pm 

Yes perl might probably live with just 3 files, but the RPM (and possibly other package managers for other distros) won't be happy. Unless we package openscap_pm.pm  as noarch and openscap_pm.so as arched, but in my opinion that would be overkill.

Example reference packages using DynaLoader same as openscap:
perl-Data-UUID-1.226-13.fc39.x86_64 having:
/usr/lib64/perl5/vendor_perl/Data/UUID.pm
/usr/lib64/perl5/vendor_perl/auto/Data/UUID/UUID.so

perl-Digest-SHA-6.04-501.fc39.x86_64 having:
/usr/lib64/perl5/vendor_perl/Digest/SHA.pm
/usr/lib64/perl5/vendor_perl/auto/Digest/SHA/SHA.so

perl-GD-2.78-3.fc39.x86_64 having:
/usr/lib64/perl5/vendor_perl/GD.pm
/usr/lib64/perl5/vendor_perl/auto/GD/GD.so

perl-Glib-1.3293-13.fc39.x86_64 having:
/usr/lib64/perl5/vendor_perl/Glib.pm
/usr/lib64/perl5/vendor_perl/auto/Glib/Glib.so

Best regards
Michal Ambroz

**Pull request merged**
