### PR TITLE
Improve error message for pcre_exec fail

### PR DESCRIPTION
**Pull request by jan-cerny**
This can help us to resolve problems similar to RHBZ#1655943.

### CODE REVIEW

**Comment by jan-cerny** [comment]
@matejak Is this what you meant? Would you like to have an human readable translation of error codes? They can be found in `man pcreapi`.

**Comment by jan-cerny** [comment]
@openscap-ci test this please

**Comment by matejak** [comment]
@jan-cerny Would it make sense to add a similar message few lines above in case the pattern can't be compiled? That could happen when people editing a datastream and introduce some typo.

**Comment by jan-cerny** [comment]
@matejak  Yes, it would, I'll do that.

**Comment by jan-cerny** [comment]
@matejak I have updated the PR with another commit.

**Pull request merged**
