### PR TITLE
Test case skipping if setup is not full vm

### PR DESCRIPTION
**Pull request by maage**
Skip / tune tests
- if no internet access
- if no full systemd environment
- if chroot
- check SELinux using selinuxenabled

### CODE REVIEW

**Comment by maage** [comment]
Seems there is some issue with failed checks: `error: %changelog entries must start with *`.

Maybe issue is that test environment does not handle `%autochangelog`. 

https://download.copr.fedorainfracloud.org/results/packit/OpenSCAP-openscap-1886/centos-stream-8-x86_64/04863323-openscap/openscap.spec
```
%changelog
%autochangelog
```
Maybe `%autochangelog` is not supported in those distros? Feature is quite new, it seems.

https://fedoraproject.org/wiki/Changes/rpmautospec

I think in test context it provides very little if any value. Maybe drop it in spec and try again.

**Comment by jan-cerny** [comment]
Yes, I have noticed the same thing, originally I thought it's a temporary problem, because it used to work before, but now I can see this in all recent PRs.

**Review by jan-cerny — APPROVED** [review]
Thanks!

**Comment by maage** [comment]
Thanks

**Pull request merged**
